In [7]:
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_columns', None)

# SETORES 2010

In [ ]:
sectors2010 = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/setores_censitarios_2010/br/setores_censitarios.shp')
sectors2010.head()

,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO,ID1,layer,path,geometry
0,17182,110009812000003,RURAL,None,None,11000981200,None,110009812,NOVO PARA�SO,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.89575 -11.35508, -60.89557 -11.3..."
1,17183,110009815000001,URBANO,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.74999 -11.3999, -60.74913 -11.40..."
2,17184,110009815000002,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.72986 -11.35738, -60.72954 -11.3..."
3,17185,110009815000003,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.91829 -11.29374, -60.916 -11.292..."
4,17186,110009815000004,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.69047 -11.38391, -60.6903 -11.38..."

In [10]:
ibp2010 = pd.read_csv('/Volumes/ssd/Doutorado/DATASET/IBP - CIDACS/ibp_setor_censitario-1.csv')
ibp2010

,Cod_setor,Cod_municipio,Nome_do_municipio,Nome_da_UF,Nome_Grande_Regiao,Cod_UF,Situacao_setor,V001_p13,V002_p13,V021_p13,V001_dr,V001_d1,V002_d1,urban,n_pop_hh,n_ph,pop_7plus,n_hh_inc_12,pcnt_hh_inc_12,z_hh_inc_12,Q_hh_inc_12,D_hh_inc_12,V_hh_inc_12,n_lit_7plus,pcnt_Nlit_7plus,z_lit_7plus,Q_Nlit_7plus,D_Nlit_7plus,V_Nlit_7plus,av_inadeq_housing,z_inadeq_housing,Q_inadeq_housing,D_inadeq_housing,V_inadeq_housing,BrazDep_measure,Q_measure,D_measure,V_measure,low95_rn,up95_rn,D_up95_rn,D_low95_rn,flag_1_rn,low95_rw,up95_rw,D_up95_rw,D_low95_rw,flag_1_rw,flag_all
0,110002305000021,1100023,ARIQUEMES,Rondônia,Região Norte,RO,1,25,NaN,NaN,NaN,7,7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,110002305000091,1100023,ARIQUEMES,Rondônia,Região Norte,RO,8,7,NaN,NaN,NaN,4,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,110004905000026,1100049,CACOAL,Rondônia,Região Norte,RO,1,15,NaN,NaN,NaN,3,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,110004905000074,1100049,CACOAL,Rondônia,Região Norte,RO,8,147,NaN,NaN,NaN,38,38,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,110004910000031,1100049,CACOAL,Rondônia,Região Norte,RO,8,24,NaN,NaN,NaN,6,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310115,350950205000138,3509502,CAMPINAS,São Paulo,Região Sudeste,SP,1,505,505.0,0.0,0.0,227,227,1,505.0,227.0,491.0,5.0,2.202643,-1.344146,1.0,1.0,1.0,491.0,0.000000,-0.968779,1.0,1.0,1.0,0.0,-0.718979,1.0,1.0,1.0,-3.031904,1.0,1.0,1.0,-3.076612,-2.918192,1.0,1.0,0.0,-3.628827,-2.472502,1.0,1.0,0.0,0
310116,350950205000140,3509502,CAMPINAS,São Paulo,Região Sudeste,SP,1,824,824.0,0.0,0.0,314,314,1,824.0,314.0,773.0,10.0,3.184713,-1.302672,1.0,1.0,1.0,772.0,0.129366,-0.955698,1.0,1.0,1.0,0.0,-0.718979,1.0,1.0,1.0,-2.977349,1.0,1.0,1.0,-3.041918,-2.868803,1.0,1.0,0.0,-3.533802,-2.454876,1.0,1.0,0.0,0
310117,350950205000144,3509502,CAMPINAS,São Paulo,Região Sudeste,SP,1,439,435.0,4.0,0.0,226,222,1,435.0,222.0,424.0,8.0,3.603604,-1.284982,1.0,1.0,1.0,424.0,0.000000,-0.968779,1.0,1.0,1.0,0.0,-0.718979,1.0,1.0,1.0,-2.972740,1.0,1.0,1.0,-3.046161,-2.830107,1.0,1.0,0.0,-3.501252,-2.465304,1.0,1.0,0.0,0
310118,350950205000147,3509502,CAMPINAS,São Paulo,Região Sudeste,SP,1,409,409.0,0.0,0.0,171,171,1,409.0,171.0,383.0,2.0,1.169591,-1.387772,1.0,1.0,1.0,380.0,0.783290,-0.889573,1.0,1.0,2.0,0.0,-0.718979,1.0,1.0,1.0,-2.996324,1.0,1.0,1.0,-3.086774,-2.873393,1.0,1.0,0.0,-3.643995,-2.412497,1.0,1.0,0.0,0
310119,350950205000148,3509502,CAMPINAS,São Paulo,Região Sudeste,SP,1,733,733.0,0.0,0.0,309,309,1,733.0,309.0,702.0,12.0,3.883495,-1.273162,1.0,1.0,2.0,702.0,0.000000,-0.968779,1.0,1.0,1.0,0.0,-0.718979,1.0,1.0,1.0,-2.960920,1.0,1.0,1.0,-3.025697,-2.841406,1.0,1.0,0.0,-3.478851,-2.463895,1.0,1.0,0.0,0

In [ ]:
sectors2010['CD_GEOCODI'] = sectors2010['CD_GEOCODI'].astype('Int64')
sectors2010 = sectors2010.merge(ibp2010, left_on='CD_GEOCODI', right_on='Cod_setor', how='left')
sectors2010

,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO,ID1,layer,path,geometry,Cod_setor,Cod_municipio,Nome_do_municipio,Nome_da_UF,Nome_Grande_Regiao,Cod_UF,Situacao_setor,V001_p13,V002_p13,V021_p13,V001_dr,V001_d1,V002_d1,urban,n_pop_hh,n_ph,pop_7plus,n_hh_inc_12,pcnt_hh_inc_12,z_hh_inc_12,Q_hh_inc_12,D_hh_inc_12,V_hh_inc_12,n_lit_7plus,pcnt_Nlit_7plus,z_lit_7plus,Q_Nlit_7plus,D_Nlit_7plus,V_Nlit_7plus,av_inadeq_housing,z_inadeq_housing,Q_inadeq_housing,D_inadeq_housing,V_inadeq_housing,BrazDep_measure,Q_measure,D_measure,V_measure,low95_rn,up95_rn,D_up95_rn,D_low95_rn,flag_1_rn,low95_rw,up95_rw,D_up95_rw,D_low95_rw,flag_1_rw,flag_all
0,17182,110009812000003,RURAL,None,None,11000981200,None,110009812,NOVO PARA�SO,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.89575 -11.35508, -60.89557 -11.3...",1.100098e+14,1100098.0,ESPIGÃO D'OESTE,Rondônia,Região Norte,RO,8.0,555.0,555.0,0.0,0.0,159.0,159.0,0.0,555.0,159.0,506.0,64.0,40.251572,0.262693,4.0,7.0,13.0,414.0,18.181818,0.869770,5.0,9.0,17.0,62.027027,1.996129,5.0,10.0,19.0,3.128592,5.0,9.0,18.0,2.617687,3.621448,9.0,9.0,0.0,1.552665,4.760466,9.0,9.0,0.0,0.0
1,17183,110009815000001,URBANO,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.74999 -11.3999, -60.74913 -11.40...",1.100098e+14,1100098.0,ESPIGÃO D'OESTE,Rondônia,Região Norte,RO,1.0,53.0,53.0,0.0,0.0,16.0,16.0,1.0,53.0,16.0,42.0,10.0,62.500000,1.202263,5.0,9.0,17.0,36.0,14.285714,0.475795,4.0,8.0,16.0,42.924528,1.159956,5.0,9.0,18.0,2.838014,5.0,9.0,17.0,1.337026,4.440641,9.0,8.0,0.0,2.029392,3.496070,9.0,9.0,0.0,0.0
2,17184,110009815000002,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.72986 -11.35738, -60.72954 -11.3...",1.100098e+14,1100098.0,ESPIGÃO D'OESTE,Rondônia,Região Norte,RO,8.0,507.0,507.0,0.0,0.0,152.0,152.0,0.0,507.0,152.0,446.0,105.0,69.078947,1.480097,5.0,9.0,18.0,402.0,9.865471,0.028819,4.0,7.0,14.0,48.274162,1.394125,5.0,9.0,18.0,2.903042,5.0,9.0,17.0,2.425636,3.328244,9.0,9.0,0.0,1.287833,4.217355,9.0,9.0,0.0,0.0
3,17185,110009815000003,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.91829 -11.29374, -60.916 -11.292...",1.100098e+14,1100098.0,ESPIGÃO D'OESTE,Rondônia,Região Norte,RO,8.0,555.0,555.0,0.0,0.0,171.0,171.0,0.0,555.0,171.0,487.0,91.0,53.216374,0.810207,4.0,8.0,16.0,400.0,17.864476,0.837680,5.0,9.0,17.0,59.729730,1.895570,5.0,10.0,19.0,3.543457,5.0,9.0,18.0,3.053697,4.024136,9.0,9.0,0.0,2.541349,4.731049,9.0,9.0,0.0,0.0
4,17186,110009815000004,RURAL,None,None,11000981500,None,110009815,FLOR DA SERRA,1100098,ESPIG�O D'OESTE,CACOAL,LESTE RONDONIENSE,NaN,11SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-60.69047 -11.38391, -60.6903 -11.38...",1.100098e+14,1100098.0,ESPIGÃO D'OESTE,Rondônia,Região Norte,RO,8.0,336.0,336.0,0.0,0.0,106.0,106.0,0.0,336.0,106.0,307.0,47.0,44.339623,0.435335,4.0,7.0,14.0,255.0,16.938111,0.744006,5.0,9.0,17.0,65.327381,2.140595,5.0,10.0,19.0,3.319936,5.0,9.0,18.0,2.694256,3.915415,9.0,9.0,0.0,1.765118,5.016311,9.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316569,4450,530010805300153,URBANO,None,None,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,5300108,BRAS�LIA,BRAS�LIA,DISTRITO FEDERAL,NaN,53SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-47.81165 -15.86005, -47.80981 -15.8...",5.300108e+14,5300108.0,BRASÍLIA,Distrito Federal,Região Centro-Oeste,DF,1.0,434.0,434.0,0.0,0.0,128.0,128.0,1.0,434.0,128.0,392.0,16.0,12.500000,-0.909279,2.0,3.0,5.0,389.0,0.765306,-0.891391,1.0,1.0,2.0,1.382488,-0.658463,2.0,4.0,8.0,-2.459134,1.0,2.0,3.0,-2.702112,-2.171187,2.0,2.0,0.0,-2.690931,-2.194227,2.0,2.0,0.0,0.0
316570,4451,530010805300154,URBANO,None,None,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,5300108,BRAS�LIA,BRAS�LIA,DISTRITO FEDERAL,NaN,53SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-47.81951 -15.8618, -47.81866 -15.85...",5.300108e+14,5300108.0,BRASÍLIA,Distrito Federal,Região Centro-Oeste,DF,1.0,534.0,534.0,0.0,0.0,170.0,170.0,1.0,534.0,170.0,479.0,1.0,0.588235,-1.412323,1.0,1.0,1.0,479.0,0.000000,-0.968779,1.0,1.0,1.0,0.000000,-0.718979,1.0,2.0,3.0,-3.100082,1.0,1.0,1.0,-3.113260,-3.009519,1.0,1.0,0.0,-3.767902,-2.485225,1.0,1.0,0.0,0.0
316571,4452,530010805300155,URBANO,None,None,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,5300108,BRAS�LIA,BRAS�LIA,DISTRITO FEDERAL,NaN,53SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-47.81758 -15.85556, -47.81269 -15.8...",5.300108e+14,5300108.0,BRASÍLIA,Distrito Federal,Região Centro-Oeste,DF,1.0,532.0,532.0,0.0,0.0,161.0,161.0,1.0,532.0,161.0,483.0,5.0,3.105590,-1.306013,1.0,1.0,1.0,483.0,0.000000,-0.968779,1.0,1.0,1.0,0.469925,-0.698409,2.0,3.0,6.0,-2.973202,1.0,1.0,1.0,-3.052725,-2.825484,1.0,1.0,0.0,-3.540752,-2.428390,1.0,1.0,0.0,0.0
316572,4453,530010805300156,URBANO,None,None,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,5300108,BRAS�LIA,BRAS�LIA,DISTRITO FEDERAL,NaN,53SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-47.7841 -15.90137, -47.78145 -15.90...",5.300108e+14,5300108.0,BRASÍLIA,Distrito Federal,Região Centro-Oeste,DF,1.0,2103.0,2103.0,0.0,0.0,536.0,536.0,1.0,2103.0,536.0,1803.0,191.0,35.634328,0.067703,3.0,6.0,12.0,1693.0,6.100943,-0.351851,3.0,6.0,11.0,0.641940,-0.690879,2.0,4.0,7.0,-0.975027,3.0,5.0,10.0,-1.189161,-0.785696,5.0,6.0,0.0,-1.655266,-0.266322,5.0,5.0,0.0,0.0
316573,4454,530010805300158,URBANO,None,None,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,5300108,BRAS�LIA,BRAS�LIA,DISTRITO FEDERAL,NaN,53SEE250GC_SIR,/Users/joaosilva/Downloads/setores_censitarios...,"POLYGON ((-47.78595 -15.92526, -47.7861 -15.92...",5.300108e+14,5300108.0,BRASÍLIA,Distrito Federal,Região Centro-Oeste,DF,1.0,169.0,0.0,169.0,0.0,169.0,0.0,1.0,0.0,0.0,169.0,0.0,NaN,NaN,NaN,NaN,NaN,154.0,8.875740,-0.071263,4.0,7.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [ ]:
sectors2010 = sectors2010[['ID', 'CD_GEOCODI', 'geometry', 'V001_p13', 'BrazDep_measure']]
sectors2010.columns = ['id', 'cod_setor', 'geometry', 'pop', 'brazdep']
sectors2010

In [ ]:
sectors2010.to_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/setores_censitarios_2010/br/setores_censitarios_pop_ibp.shp')

/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/geopandas.py:662: UserWarning: 'crs' was not provided.  The output dataset will not have projection information defined and may not be usable in other systems.
  write(

# SETORES 2022

In [ ]:
sectors2022 = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/setores_censitarios_2022/br/setores_censitarios_br.shp')
sectors2022.head()

,CD_SETOR,SITUACAO,CD_SIT,CD_TIPO,AREA_KM2,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,NM_MUN,CD_DIST,NM_DIST,CD_SUBDIST,NM_SUBDIST,CD_BAIRRO,NM_BAIRRO,CD_NU,NM_NU,CD_FCU,NM_FCU,CD_AGLOM,NM_AGLOM,CD_RGINT,NM_RGINT,CD_RGI,NM_RGI,CD_CONCURB,NM_CONCURB,layer,path,geometry
0,120001305000001,Urbana,1,0,0.406588,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.04925 -10.07069, -67.04938 -10.0..."
1,120001305000002,Urbana,2,0,1.381775,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.03937 -10.07846, -67.03897 -10.0..."
2,120001305000005,Rural,8,0,134.976623,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.03598 -10.00512, -67.03653 -10.0..."
3,120001305000006,Rural,8,0,168.897036,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-66.91526 -9.86712, -66.91544 -9.867..."
4,120001305000007,Rural,8,0,107.953840,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-66.88699 -9.83206, -66.88808 -9.832..."

In [ ]:
agg_sectors = pd.read_csv('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/Agregados_por_setores_basico_BR_2022.csv', sep=';', encoding='latin-1')
agg_sectors

In [ ]:
sectors2022['CD_SETOR'] = sectors2022['CD_SETOR'].astype('Int64')
sectors2022 = sectors2022.merge(agg_sectors, left_on='CD_SETOR', right_on='CD_SETOR', how='left')
sectors2022

,CD_SETOR,SITUACAO_x,CD_SIT_x,CD_TIPO_x,AREA_KM2_x,CD_REGIAO_x,NM_REGIAO_x,CD_UF_x,NM_UF_x,CD_MUN_x,NM_MUN_x,CD_DIST_x,NM_DIST_x,CD_SUBDIST_x,NM_SUBDIST_x,CD_BAIRRO_x,NM_BAIRRO_x,CD_NU_x,NM_NU_x,CD_FCU_x,NM_FCU_x,CD_AGLOM_x,NM_AGLOM_x,CD_RGINT_x,NM_RGINT_x,CD_RGI_x,NM_RGI_x,CD_CONCURB_x,NM_CONCURB_x,layer,path,geometry,SITUACAO_y,CD_SIT_y,CD_TIPO_y,AREA_KM2_y,CD_REGIAO_y,NM_REGIAO_y,CD_UF_y,NM_UF_y,CD_MUN_y,NM_MUN_y,CD_DIST_y,NM_DIST_y,CD_SUBDIST_y,NM_SUBDIST_y,CD_BAIRRO_y,NM_BAIRRO_y,CD_NU_y,NM_NU_y,CD_FCU_y,NM_FCU_y,CD_AGLOM_y,NM_AGLOM_y,CD_RGINT_y,NM_RGINT_y,CD_RGI_y,NM_RGI_y,CD_CONCURB_y,NM_CONCURB_y,v0001,v0002,v0003,v0004,v0005,v0006,v0007
0,120001305000001,Urbana,1,0,0.406588,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.04925 -10.07069, -67.04938 -10.0...",Urbana,1,0,"0,4065884",1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1201,Rio Branco,120001,Rio Branco,.,NaN,920,333,328,5,"3,0","0,0000",309
1,120001305000002,Urbana,2,0,1.381775,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.03937 -10.07846, -67.03897 -10.0...",Urbana,2,0,"1,3817746",1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1201,Rio Branco,120001,Rio Branco,.,NaN,354,112,112,0,"3,2","0,0000",109
2,120001305000005,Rural,8,0,134.976623,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-67.03598 -10.00512, -67.03653 -10.0...",Rural,8,0,"134,9766226",1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1201,Rio Branco,120001,Rio Branco,.,NaN,278,164,164,0,"2,8","0,0000",100
3,120001305000006,Rural,8,0,168.897036,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-66.91526 -9.86712, -66.91544 -9.867...",Rural,8,0,"168,8970359",1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1201,Rio Branco,120001,Rio Branco,.,NaN,401,191,190,1,"3,0","0,0149",134
4,120001305000007,Rural,8,0,107.953840,1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,None,None,None,None,None,None,None,None,None,1201,Rio Branco,120001,Rio Branco,None,None,AC_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-66.88699 -9.83206, -66.88808 -9.832...",Rural,8,0,"107,9538404",1,Norte,12,Acre,1200013,Acrelândia,120001305,Acrelândia,12000130500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1201,Rio Branco,120001,Rio Branco,.,NaN,241,128,128,0,"2,8","0,0118",85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489073,172210705000030,Urbana,1,1,0.075021,1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,None,None,None,None,None,17221070001,Jandir Malinski,None,None,1702,Araguaína,170005,Araguaína,None,None,TO_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-48.53139 -6.41658, -48.53136 -6.416...",Urbana,1,1,"0,0750205",1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,NaN,.,NaN,.,NaN,17221070001,Jandir Malinski,.,NaN,1702,Araguaína,170005,Araguaína,.,NaN,276,114,114,0,"3,0","0,0000",91
489074,172210705000031,Urbana,1,0,0.059690,1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,None,None,None,None,None,None,None,None,None,1702,Araguaína,170005,Araguaína,None,None,TO_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-48.52973 -6.41638, -48.52999 -6.416...",Urbana,1,0,"0,0596902",1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1702,Araguaína,170005,Araguaína,.,NaN,289,97,97,0,"3,1","0,0000",92
489075,172210705000032,Urbana,1,0,0.144457,1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,None,None,None,None,None,None,None,None,None,1702,Araguaína,170005,Araguaína,None,None,TO_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-48.53265 -6.41567, -48.53287 -6.415...",Urbana,1,0,"0,1444573",1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1702,Araguaína,170005,Araguaína,.,NaN,152,64,64,0,"2,9","0,0000",53
489076,172210705000034,Urbana,1,0,0.170880,1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,None,None,None,None,None,None,None,None,None,1702,Araguaína,170005,Araguaína,None,None,TO_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-48.53492 -6.41734, -48.53513 -6.417...",Urbana,1,0,"0,1708797",1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,NaN,.,NaN,.,NaN,.,NaN,.,NaN,1702,Araguaína,170005,Araguaína,.,NaN,393,176,175,1,"2,8","0,0000",142
489077,172210705000036,Urbana,1,1,0.131574,1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,None,None,None,None,None,17221070001,Jandir Malinski,None,None,1702,Araguaína,170005,Araguaína,None,None,TO_setores_CD2022,/Volumes/ssd/Doutorado/DATASET/IBGE/setores ce...,"POLYGON ((-48.53205 -6.41989, -48.53202 -6.419...",Urbana,1,1,"0,1315736",1,Norte,17,Tocantins,1722107,Xambioá,172210705,Xambioá,17221070500,NaN,.,NaN,.,NaN,17221070001,Jandir Malinski,.,NaN,1702,Araguaína,170005,Araguaína,.,NaN,388,149,149,0,"3,5","0,0090",111

In [ ]:
sectors2022 = sectors2022[['CD_SETOR', 'geometry', 'v0001', 'CD_FCU_x']]
sectors2022.columns = ['cod_setor', 'geometry', 'pop', 'cd_fcu']
sectors2022

,cod_setor,geometry,pop,cd_fcu
0,120001305000001,"POLYGON ((-67.04925 -10.07069, -67.04938 -10.0...",920,None
1,120001305000002,"POLYGON ((-67.03937 -10.07846, -67.03897 -10.0...",354,None
2,120001305000005,"POLYGON ((-67.03598 -10.00512, -67.03653 -10.0...",278,None
3,120001305000006,"POLYGON ((-66.91526 -9.86712, -66.91544 -9.867...",401,None
4,120001305000007,"POLYGON ((-66.88699 -9.83206, -66.88808 -9.832...",241,None
...,...,...,...,...
489073,172210705000030,"POLYGON ((-48.53139 -6.41658, -48.53136 -6.416...",276,17221070001
489074,172210705000031,"POLYGON ((-48.52973 -6.41638, -48.52999 -6.416...",289,None
489075,172210705000032,"POLYGON ((-48.53265 -6.41567, -48.53287 -6.415...",152,None
489076,172210705000034,"POLYGON ((-48.53492 -6.41734, -48.53513 -6.417...",393,None
489077,172210705000036,"POLYGON ((-48.53205 -6.41989, -48.53202 -6.419...",388,17221070001

In [ ]:
sectors2022.to_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Setores Censitários/setores_censitarios_2022/br/setores_censitarios_pop_fcu.shp')