In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import shape
pd.set_option('display.max_columns', None)

In [2]:
fcu = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/fcu_blank/qg_2022_670_fcu_agreg.shp')
fcu

,cd_fcu,nm_fcu,cd_uf,nm_uf,sigla_uf,cd_mun,nm_mun,geometry
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-46.37112 -23.5, -46.37141 -23.5001,..."
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-49.05007 -26.93529, -49.05009 -26.9..."
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.48263 -22.8887, -43.48252 -22.88..."
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.21664 -22.87497, -43.21662 -22.8..."
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-47.01387 -22.91975, -47.01458 -22.9..."
...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-35.76558 -9.57082, -35.76767 -9.572..."
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-37.08826 -10.94031, -37.08824 -10.9..."
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-46.39452 -23.37916, -46.3949 -23.37..."
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.95091 -8.04458, -34.95088 -8.044..."
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-37.34702 -5.14423, -37.34723 -5.145..."

In [3]:
# df = pd.read_csv('/Users/joaopedro/workspace/doutorado/DATASET/mapbiomas/Slum_Band_Areas_2023.csv')
df = pd.read_csv('./dataset/map-biomas.csv')
df
# df['geometry'] = df['.geo'].apply(lambda x: shape(eval(x)))

# Criar um GeoDataFrame
# gdf = gpd.GeoDataFrame(df, geometry='geometry')
# gdf
# Salvar o GeoDataFrame

,system:index,cd_fcu,cd_mun,cd_uf,name,nm_fcu,nm_mun,nm_uf,sigla_uf,slum_analysis_1985_agua,slum_analysis_1985_area_favela,slum_analysis_1985_decliv_10,slum_analysis_1985_decliv_20,slum_analysis_1985_decliv_30,slum_analysis_1985_decliv_mais_30,slum_analysis_1985_frag_veg,slum_analysis_1985_hand_acima_6,slum_analysis_1985_hand_ate_3,slum_analysis_1985_hand_ate_6,slum_analysis_1985_risco,slum_analysis_1985_sem_risco,slum_analysis_1985_sem_veg_intraurb,slum_analysis_1985_veg_intra_urb,slum_analysis_1986_agua,slum_analysis_1986_area_favela,slum_analysis_1986_decliv_10,slum_analysis_1986_decliv_20,slum_analysis_1986_decliv_30,slum_analysis_1986_decliv_mais_30,slum_analysis_1986_frag_veg,slum_analysis_1986_hand_acima_6,slum_analysis_1986_hand_ate_3,slum_analysis_1986_hand_ate_6,slum_analysis_1986_risco,slum_analysis_1986_sem_risco,slum_analysis_1986_sem_veg_intraurb,slum_analysis_1986_veg_intra_urb,slum_analysis_1987_agua,slum_analysis_1987_area_favela,slum_analysis_1987_decliv_10,slum_analysis_1987_decliv_20,slum_analysis_1987_decliv_30,slum_analysis_1987_decliv_mais_30,slum_analysis_1987_frag_veg,slum_analysis_1987_hand_acima_6,slum_analysis_1987_hand_ate_3,slum_analysis_1987_hand_ate_6,slum_analysis_1987_risco,slum_analysis_1987_sem_risco,slum_analysis_1987_sem_veg_intraurb,slum_analysis_1987_veg_intra_urb,slum_analysis_1988_agua,slum_analysis_1988_area_favela,slum_analysis_1988_decliv_10,slum_analysis_1988_decliv_20,slum_analysis_1988_decliv_30,slum_analysis_1988_decliv_mais_30,slum_analysis_1988_frag_veg,slum_analysis_1988_hand_acima_6,slum_analysis_1988_hand_ate_3,slum_analysis_1988_hand_ate_6,slum_analysis_1988_risco,slum_analysis_1988_sem_risco,slum_analysis_1988_sem_veg_intraurb,slum_analysis_1988_veg_intra_urb,slum_analysis_1989_agua,slum_analysis_1989_area_favela,slum_analysis_1989_decliv_10,slum_analysis_1989_decliv_20,slum_analysis_1989_decliv_30,slum_analysis_1989_decliv_mais_30,slum_analysis_1989_frag_veg,slum_analysis_1989_hand_acima_6,slum_analysis_1989_hand_ate_3,slum_analysis_1989_hand_ate_6,slum_analysis_1989_risco,slum_analysis_1989_sem_risco,slum_analysis_1989_sem_veg_intraurb,slum_analysis_1989_veg_intra_urb,slum_analysis_1990_agua,slum_analysis_1990_area_favela,slum_analysis_1990_decliv_10,slum_analysis_1990_decliv_20,slum_analysis_1990_decliv_30,slum_analysis_1990_decliv_mais_30,slum_analysis_1990_frag_veg,slum_analysis_1990_hand_acima_6,slum_analysis_1990_hand_ate_3,slum_analysis_1990_hand_ate_6,slum_analysis_1990_risco,slum_analysis_1990_sem_risco,slum_analysis_1990_sem_veg_intraurb,slum_analysis_1990_veg_intra_urb,slum_analysis_1991_agua,slum_analysis_1991_area_favela,slum_analysis_1991_decliv_10,slum_analysis_1991_decliv_20,slum_analysis_1991_decliv_30,slum_analysis_1991_decliv_mais_30,slum_analysis_1991_frag_veg,slum_analysis_1991_hand_acima_6,slum_analysis_1991_hand_ate_3,slum_analysis_1991_hand_ate_6,slum_analysis_1991_risco,slum_analysis_1991_sem_risco,slum_analysis_1991_sem_veg_intraurb,slum_analysis_1991_veg_intra_urb,slum_analysis_1992_agua,slum_analysis_1992_area_favela,slum_analysis_1992_decliv_10,slum_analysis_1992_decliv_20,slum_analysis_1992_decliv_30,slum_analysis_1992_decliv_mais_30,slum_analysis_1992_frag_veg,slum_analysis_1992_hand_acima_6,slum_analysis_1992_hand_ate_3,slum_analysis_1992_hand_ate_6,slum_analysis_1992_risco,slum_analysis_1992_sem_risco,slum_analysis_1992_sem_veg_intraurb,slum_analysis_1992_veg_intra_urb,slum_analysis_1993_agua,slum_analysis_1993_area_favela,slum_analysis_1993_decliv_10,slum_analysis_1993_decliv_20,slum_analysis_1993_decliv_30,slum_analysis_1993_decliv_mais_30,slum_analysis_1993_frag_veg,slum_analysis_1993_hand_acima_6,slum_analysis_1993_hand_ate_3,slum_analysis_1993_hand_ate_6,slum_analysis_1993_risco,slum_analysis_1993_sem_risco,slum_analysis_1993_sem_veg_intraurb,slum_analysis_1993_veg_intra_urb,slum_analysis_1994_agua,slum_analysis_1994_area_favela,slum_analysis_1994_decliv_10,slum_analysis_1994_decliv_20,slum_analysis_1994_decliv_30,slum_analysis_1994_decliv_mais_30,slum_analysis_1994_frag_veg,slum_analysis_1994_hand_acima_6,slum_analysis_1994_hand_ate_3,slum_analysis_1994_hand_ate_6,slum_analysis_1994_risco,slum_analysis_1994_sem_risco,slum_analysis_1994_sem_veg_intraurb,slum_analysis_1994_veg_intra_urb,slum_analysis_1995_agua,slum_analysis_1995_area_favela,slum_analysis_1995_decliv_10,slum_analysis_1995_decliv_20,slum_analysis_1995_decliv_30,slum_analysis_1995_decliv_mais_30,slum_analysis_1995_frag_veg,slum_analysis_1995_hand_acima_6,slum_analysis_1995_hand_ate_3,slum_analysis_1995_hand_ate_6,slum_analysis_1995_risco,slum_analysis_1995_sem_risco,slum_analysis_1995_sem_veg_intraurb,slum_analysis_1995_veg_intra_urb,slum_analysis_1996_agua,slum_analysis_1996_area_favela,slum_analysis_1996_decliv_10,slum_analysis_1996_decliv_20,slum_analysis_1996_decliv_30,slum_analysis_1996_decliv_mais_30,slum_analysis_1996_frag_veg,slum_analysis_1996_hand_acima_6,slum_analysis_1996_hand_ate_3,slum_analysis_1996_hand_ate_6,slum_analysis_1996_risco,slum_analysis_1996_sem_risco,slum_analysis_1996_sem_veg_intraurb,slum_analysis_1996_veg_intra_urb,slum_analysis_1997_agua,slum_analysis_1997_area_favela,slum_analysis_1997_decliv_10,slum_analysis_1997_decliv_20,slum_analysis_1997_decliv_30,slum_analysis_1997_decliv_mais_30,slum_analysis_1997_frag_veg,slum_analysis_1997_hand_acima_6,slum_analysis_1997_hand_ate_3,slum_analysis_1997_hand_ate_6,slum_analysis_1997_risco,slum_analysis_1997_sem_risco,slum_analysis_1997_sem_veg_intraurb,slum_analysis_1997_veg_intra_urb,slum_analysis_1998_agua,slum_analysis_1998_area_favela,slum_analysis_1998_decliv_10,slum_analysis_1998_decliv_20,slum_analysis_1998_decliv_30,slum_analysis_1998_decliv_mais_30,slum_analysis_1998_frag_veg,slum_analysis_1998_hand_acima_6,slum_analysis_1998_hand_ate_3,slum_analysis_1998_hand_ate_6,slum_analysis_1998_risco,slum_analysis_1998_sem_risco,slum_analysis_1998_sem_veg_intraurb,slum_analysis_1998_veg_intra_urb,slum_analysis_1999_agua,slum_analysis_1999_area_favela,slum_analysis_1999_decliv_10,slum_analysis_1999_decliv_20,slum_analysis_1999_decliv_30,slum_analysis_1999_decliv_mais_30,slum_analysis_1999_frag_veg,slum_analysis_1999_hand_acima_6,slum_analysis_1999_hand_ate_3,slum_analysis_1999_hand_ate_6,slum_analysis_1999_risco,slum_analysis_1999_sem_risco,slum_analysis_1999_sem_veg_intraurb,slum_analysis_1999_veg_intra_urb,slum_analysis_2000_agua,slum_analysis_2000_area_favela,slum_analysis_2000_decliv_10,slum_analysis_2000_decliv_20,slum_analysis_2000_decliv_30,slum_analysis_2000_decliv_mais_30,slum_analysis_2000_frag_veg,slum_analysis_2000_hand_acima_6,slum_analysis_2000_hand_ate_3,slum_analysis_2000_hand_ate_6,slum_analysis_2000_risco,slum_analysis_2000_sem_risco,slum_analysis_2000_sem_veg_intraurb,slum_analysis_2000_veg_intra_urb,slum_analysis_2001_agua,slum_analysis_2001_area_favela,slum_analysis_2001_decliv_10,slum_analysis_2001_decliv_20,slum_analysis_2001_decliv_30,slum_analysis_2001_decliv_mais_30,slum_analysis_2001_frag_veg,slum_analysis_2001_hand_acima_6,slum_analysis_2001_hand_ate_3,slum_analysis_2001_hand_ate_6,slum_analysis_2001_risco,slum_analysis_2001_sem_risco,slum_analysis_2001_sem_veg_intraurb,slum_analysis_2001_veg_intra_urb,slum_analysis_2002_agua,slum_analysis_2002_area_favela,slum_analysis_2002_decliv_10,slum_analysis_2002_decliv_20,slum_analysis_2002_decliv_30,slum_analysis_2002_decliv_mais_30,slum_analysis_2002_frag_veg,slum_analysis_2002_hand_acima_6,slum_analysis_2002_hand_ate_3,slum_analysis_2002_hand_ate_6,slum_analysis_2002_risco,slum_analysis_2002_sem_risco,slum_analysis_2002_sem_veg_intraurb,slum_analysis_2002_veg_intra_urb,slum_analysis_2003_agua,slum_analysis_2003_area_favela,slum_analysis_2003_decliv_10,slum_analysis_2003_decliv_20,slum_analysis_2003_decliv_30,slum_analysis_2003_decliv_mais_30,slum_analysis_2003_frag_veg,slum_analysis_2003_hand_acima_6,slum_analysis_2003_hand_ate_3,slum_analysis_2003_hand_ate_6,slum_analysis_2003_risco,slum_analysis_2003_sem_risco,slum_analysis_2003_sem_veg_intraurb,slum_analysis_2003_veg_intra_urb,slum_analysis_2004_agua,slum_analysis_2004_area_favela,slum_analysis_2004_decliv_10,slum_analysis_2004_decliv_20,slum_analysis_2004_decliv_30,slum_analysis_2004_decliv_mais_30,slum_analysis_2004_frag_veg,slum_analysis_2004_hand_acima_6,slum_analysis_2004_hand_ate_3,slum_analysis_2004_hand_ate_6,slum_analysis_2004_risco,slum_analysis_2004_sem_risco,slum_analysis_2004_sem_veg_intraurb,slum_analysis_2004_veg_intra_urb,slum_analysis_2005_agua,slum_analysis_2005_area_favela,slum_analysis_2005_decliv_10,slum_analysis_2005_decliv_20,slum_analysis_2005_decliv_30,slum_analysis_2005_decliv_mais_30,slum_analysis_2005_frag_veg,slum_analysis_2005_hand_acima_6,slum_analysis_2005_hand_ate_3,slum_analysis_2005_hand_ate_6,slum_analysis_2005_risco,slum_analysis_2005_sem_risco,slum_analysis_2005_sem_veg_intraurb,slum_analysis_2005_veg_intra_urb,slum_analysis_2006_agua,slum_analysis_2006_area_favela,slum_analysis_2006_decliv_10,slum_analysis_2006_decliv_20,slum_analysis_2006_decliv_30,slum_analysis_2006_decliv_mais_30,slum_analysis_2006_frag_veg,slum_analysis_2006_hand_acima_6,slum_analysis_2006_hand_ate_3,slum_analysis_2006_hand_ate_6,slum_analysis_2006_risco,slum_analysis_2006_sem_risco,slum_analysis_2006_sem_veg_intraurb,slum_analysis_2006_veg_intra_urb,slum_analysis_2007_agua,slum_analysis_2007_area_favela,slum_analysis_2007_decliv_10,slum_analysis_2007_decliv_20,slum_analysis_2007_decliv_30,slum_analysis_2007_decliv_mais_30,slum_analysis_2007_frag_veg,slum_analysis_2007_hand_acima_6,slum_analysis_2007_hand_ate_3,slum_analysis_2007_hand_ate_6,slum_analysis_2007_risco,slum_analysis_2007_sem_risco,slum_analysis_2007_sem_veg_intraurb,slum_analysis_2007_veg_intra_urb,slum_analysis_2008_agua,slum_analysis_2008_area_favela,slum_analysis_2008_decliv_10,slum_analysis_2008_decliv_20,slum_analysis_2008_decliv_30,slum_analysis_2008_decliv_mais_30,slum_analysis_2008_frag_veg,slum_analysis_2008_hand_acima_6,slum_analysis_2008_hand_ate_3,slum_analysis_2008_hand_ate_6,slum_analysis_2008_risco,slum_analysis_2008_sem_risco,slum_analysis_2008_sem_veg_intraurb,slum_analysis_2008_veg_intra_urb,slum_analysis_2009_agua,slum_analysis_2009_area_favela,slum_analysis_2009_decliv_10,slum_analysis_2009_decliv_20,slum_analysis_2009_decliv_30,slum_analysis_2009_decliv_mais_30,slum_analysis_2009_frag_veg,slum_analysis_2009_hand_acima_6,slum_analysis_2009_hand_ate_3,slum_analysis_2009_hand_ate_6,slum_analysis_2009_risco,slum_analysis_2009_sem_risco,slum_analysis_2009_sem_veg_intraurb,slum_analysis_2009_veg_intra_urb,slum_analysis_2010_agua,slum_analysis_2010_area_favela,slum_analysis_2010_decliv_10,slum_analysis_2010_decliv_20,slum_analysis_2010_decliv_30,slum_analysis_2010_decliv_mais_30,slum_analysis_2010_frag_veg,slum_analysis_2010_hand_acima_6,slum_analysis_2010_hand_ate_3,slum_analysis_2010_hand_ate_6,slum_analysis_2010_risco,slum_analysis_2010_sem_risco,slum_analysis_2010_sem_veg_intraurb,slum_analysis_2010_veg_intra_urb,slum_analysis_2011_agua,slum_analysis_2011_area_favela,slum_analysis_2011_decliv_10,slum_analysis_2011_decliv_20,slum_analysis_2011_decliv_30,slum_analysis_2011_decliv_mais_30,slum_analysis_2011_frag_veg,slum_analysis_2011_hand_acima_6,slum_analysis_2011_hand_ate_3,slum_analysis_2011_hand_ate_6,slum_analysis_2011_risco,slum_analysis_2011_sem_risco,slum_analysis_2011_sem_veg_intraurb,slum_analysis_2011_veg_intra_urb,slum_analysis_2012_agua,slum_analysis_2012_area_favela,slum_analysis_2012_decliv_10,slum_analysis_2012_decliv_20,slum_analysis_2012_decliv_30,slum_analysis_2012_decliv_mais_30,slum_analysis_2012_frag_veg,slum_analysis_2012_hand_acima_6,slum_analysis_2012_hand_ate_3,slum_analysis_2012_hand_ate_6,slum_analysis_2012_risco,slum_analysis_2012_sem_risco,slum_analysis_2012_sem_veg_intraurb,slum_analysis_2012_veg_intra_urb,slum_analysis_2013_agua,slum_analysis_2013_area_favela,slum_analysis_2013_decliv_10,slum_analysis_2013_decliv_20,slum_analysis_2013_decliv_30,slum_analysis_2013_decliv_mais_30,slum_analysis_2013_frag_veg,slum_analysis_2013_hand_acima_6,slum_analysis_2013_hand_ate_3,slum_analysis_2013_hand_ate_6,slum_analysis_2013_risco,slum_analysis_2013_sem_risco,slum_analysis_2013_sem_veg_intraurb,slum_analysis_2013_veg_intra_urb,slum_analysis_2014_agua,slum_analysis_2014_area_favela,slum_analysis_2014_decliv_10,slum_analysis_2014_decliv_20,slum_analysis_2014_decliv_30,slum_analysis_2014_decliv_mais_30,slum_analysis_2014_frag_veg,slum_analysis_2014_hand_acima_6,slum_analysis_2014_hand_ate_3,slum_analysis_2014_hand_ate_6,slum_analysis_2014_risco,slum_analysis_2014_sem_risco,slum_analysis_2014_sem_veg_intraurb,slum_analysis_2014_veg_intra_urb,slum_analysis_2015_agua,slum_analysis_2015_area_favela,slum_analysis_2015_decliv_10,slum_analysis_2015_decliv_20,slum_analysis_2015_decliv_30,slum_analysis_2015_decliv_mais_30,slum_analysis_2015_frag_veg,slum_analysis_2015_hand_acima_6,slum_analysis_2015_hand_ate_3,slum_analysis_2015_hand_ate_6,slum_analysis_2015_risco,slum_analysis_2015_sem_risco,slum_analysis_2015_sem_veg_intraurb,slum_analysis_2015_veg_intra_urb,slum_analysis_2016_agua,slum_analysis_2016_area_favela,slum_analysis_2016_decliv_10,slum_analysis_2016_decliv_20,slum_analysis_2016_decliv_30,slum_analysis_2016_decliv_mais_30,slum_analysis_2016_frag_veg,slum_analysis_2016_hand_acima_6,slum_analysis_2016_hand_ate_3,slum_analysis_2016_hand_ate_6,slum_analysis_2016_risco,slum_analysis_2016_sem_risco,slum_analysis_2016_sem_veg_intraurb,slum_analysis_2016_veg_intra_urb,slum_analysis_2017_agua,slum_analysis_2017_area_favela,slum_analysis_2017_decliv_10,slum_analysis_2017_decliv_20,slum_analysis_2017_decliv_30,slum_analysis_2017_decliv_mais_30,slum_analysis_2017_frag_veg,slum_analysis_2017_hand_acima_6,slum_analysis_2017_hand_ate_3,slum_analysis_2017_hand_ate_6,slum_analysis_2017_risco,slum_analysis_2017_sem_risco,slum_analysis_2017_sem_veg_intraurb,slum_analysis_2017_veg_intra_urb,slum_analysis_2018_agua,slum_analysis_2018_area_favela,slum_analysis_2018_decliv_10,slum_analysis_2018_decliv_20,slum_analysis_2018_decliv_30,slum_analysis_2018_decliv_mais_30,slum_analysis_2018_frag_veg,slum_analysis_2018_hand_acima_6,slum_analysis_2018_hand_ate_3,slum_analysis_2018_hand_ate_6,slum_analysis_2018_risco,slum_analysis_2018_sem_risco,slum_analysis_2018_sem_veg_intraurb,slum_analysis_2018_veg_intra_urb,slum_analysis_2019_agua,slum_analysis_2019_area_favela,slum_analysis_2019_decliv_10,slum_analysis_2019_decliv_20,slum_analysis_2019_decliv_30,slum_analysis_2019_decliv_mais_30,slum_analysis_2019_frag_veg,slum_analysis_2019_hand_acima_6,slum_analysis_2019_hand_ate_3,slum_analysis_2019_hand_ate_6,slum_analysis_2019_risco,slum_analysis_2019_sem_risco,slum_analysis_2019_sem_veg_intraurb,slum_analysis_2019_veg_intra_urb,slum_analysis_2020_agua,slum_analysis_2020_area_favela,slum_analysis_2020_decliv_10,slum_analysis_2020_decliv_20,slum_analysis_2020_decliv_30,slum_analysis_2020_decliv_mais_30,slum_analysis_2020_frag_veg,slum_analysis_2020_hand_acima_6,slum_analysis_2020_hand_ate_3,slum_analysis_2020_hand_ate_6,slum_analysis_2020_risco,slum_analysis_2020_sem_risco,slum_analysis_2020_sem_veg_intraurb,slum_analysis_2020_veg_intra_urb,slum_analysis_2021_agua,slum_analysis_2021_area_favela,slum_analysis_2021_decliv_10,slum_analysis_2021_decliv_20,slum_analysis_2021_decliv_30,slum_analysis_2021_decliv_mais_30,slum_analysis_2021_frag_veg,slum_analysis_2021_hand_acima_6,slum_analysis_2021_hand_ate_3,slum_analysis_2021_hand_ate_6,slum_analysis_2021_risco,slum_analysis_2021_sem_risco,slum_analysis_2021_sem_veg_intraurb,slum_analysis_2021_veg_intra_urb,slum_analysis_2022_agua,slum_analysis_2022_area_favela,slum_analysis_2022_decliv_10,slum_analysis_2022_decliv_20,slum_analysis_2022_decliv_30,slum_analysis_2022_decliv_mais_30,slum_analysis_2022_frag_veg,slum_analysis_2022_hand_acima_6,slum_analysis_2022_hand_ate_3,slum_analysis_2022_hand_ate_6,slum_analysis_2022_risco,slum_analysis_2022_sem_risco,slum_analysis_2022_sem_veg_intraurb,slum_analysis_2022_veg_intra_urb,slum_analysis_2023_agua,slum_analysis_2023_area_favela,slum_analysis_2023_decliv_10,slum_analysis_2023_decliv_20,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb,.geo

In [4]:
# filter coluns that have _2023_ in the name + cd_fcu + geometry
filtered = df.filter(regex='_2023_|cd_fcu')
filtered

,cd_fcu,slum_analysis_2023_agua,slum_analysis_2023_area_favela,slum_analysis_2023_decliv_10,slum_analysis_2023_decliv_20,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb
0,11000490002,0.0,6.188647e+03,6.188647e+03,0.000000,0.000000,0.00000,0.000000,3644.426110,0.000000,2544.221275,0.0,6.188647e+03,6.188647e+03,0.000000
1,11000490006,0.0,6.730390e+04,5.194176e+04,15362.133349,0.000000,0.00000,0.000000,28399.989870,13151.348999,25752.558219,0.0,6.730390e+04,5.317268e+04,14131.215856
2,11001060004,0.0,2.061928e+05,2.035570e+05,2635.838196,0.000000,0.00000,0.000000,86327.064626,57901.745502,61964.008470,0.0,2.061928e+05,1.394187e+05,66774.124700
3,11001060005,0.0,3.397500e+05,3.296574e+05,10092.618700,0.000000,0.00000,5271.951294,56234.646057,184846.512453,98668.819082,0.0,3.397500e+05,2.826371e+05,51840.937378
4,11001060006,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,53001080095,0.0,2.689058e+05,1.068985e+05,135013.989251,26993.307252,0.00000,0.000000,167255.999382,58611.054382,43038.703923,0.0,2.689058e+05,2.516503e+05,17255.451817
12344,53001080029,0.0,8.034488e+05,7.526489e+05,50799.935714,0.000000,0.00000,38021.235557,518693.084506,181547.760760,103207.991824,0.0,8.034488e+05,7.596298e+05,5797.755312
12345,53001080037,0.0,1.197276e+06,1.099458e+06,88308.991979,7895.788985,1613.64021,0.000000,830121.734425,223890.284913,143264.306092,0.0,1.197276e+06,1.143224e+06,54052.648084
12346,53001080031,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.000000
12347,53001080063,0.0,4.363934e+04,4.363934e+04,0.000000,0.000000,0.00000,0.000000,13480.815312,25126.479806,5032.046370,0.0,4.363934e+04,4.363934e+04,0.000000

In [5]:
nulls = df[df['slum_analysis_2023_area_favela'] == 0]
nulls

,system:index,cd_fcu,cd_mun,cd_uf,name,nm_fcu,nm_mun,nm_uf,sigla_uf,slum_analysis_1985_agua,slum_analysis_1985_area_favela,slum_analysis_1985_decliv_10,slum_analysis_1985_decliv_20,slum_analysis_1985_decliv_30,slum_analysis_1985_decliv_mais_30,slum_analysis_1985_frag_veg,slum_analysis_1985_hand_acima_6,slum_analysis_1985_hand_ate_3,slum_analysis_1985_hand_ate_6,slum_analysis_1985_risco,slum_analysis_1985_sem_risco,slum_analysis_1985_sem_veg_intraurb,slum_analysis_1985_veg_intra_urb,slum_analysis_1986_agua,slum_analysis_1986_area_favela,slum_analysis_1986_decliv_10,slum_analysis_1986_decliv_20,slum_analysis_1986_decliv_30,slum_analysis_1986_decliv_mais_30,slum_analysis_1986_frag_veg,slum_analysis_1986_hand_acima_6,slum_analysis_1986_hand_ate_3,slum_analysis_1986_hand_ate_6,slum_analysis_1986_risco,slum_analysis_1986_sem_risco,slum_analysis_1986_sem_veg_intraurb,slum_analysis_1986_veg_intra_urb,slum_analysis_1987_agua,slum_analysis_1987_area_favela,slum_analysis_1987_decliv_10,slum_analysis_1987_decliv_20,slum_analysis_1987_decliv_30,slum_analysis_1987_decliv_mais_30,slum_analysis_1987_frag_veg,slum_analysis_1987_hand_acima_6,slum_analysis_1987_hand_ate_3,slum_analysis_1987_hand_ate_6,slum_analysis_1987_risco,slum_analysis_1987_sem_risco,slum_analysis_1987_sem_veg_intraurb,slum_analysis_1987_veg_intra_urb,slum_analysis_1988_agua,slum_analysis_1988_area_favela,slum_analysis_1988_decliv_10,slum_analysis_1988_decliv_20,slum_analysis_1988_decliv_30,slum_analysis_1988_decliv_mais_30,slum_analysis_1988_frag_veg,slum_analysis_1988_hand_acima_6,slum_analysis_1988_hand_ate_3,slum_analysis_1988_hand_ate_6,slum_analysis_1988_risco,slum_analysis_1988_sem_risco,slum_analysis_1988_sem_veg_intraurb,slum_analysis_1988_veg_intra_urb,slum_analysis_1989_agua,slum_analysis_1989_area_favela,slum_analysis_1989_decliv_10,slum_analysis_1989_decliv_20,slum_analysis_1989_decliv_30,slum_analysis_1989_decliv_mais_30,slum_analysis_1989_frag_veg,slum_analysis_1989_hand_acima_6,slum_analysis_1989_hand_ate_3,slum_analysis_1989_hand_ate_6,slum_analysis_1989_risco,slum_analysis_1989_sem_risco,slum_analysis_1989_sem_veg_intraurb,slum_analysis_1989_veg_intra_urb,slum_analysis_1990_agua,slum_analysis_1990_area_favela,slum_analysis_1990_decliv_10,slum_analysis_1990_decliv_20,slum_analysis_1990_decliv_30,slum_analysis_1990_decliv_mais_30,slum_analysis_1990_frag_veg,slum_analysis_1990_hand_acima_6,slum_analysis_1990_hand_ate_3,slum_analysis_1990_hand_ate_6,slum_analysis_1990_risco,slum_analysis_1990_sem_risco,slum_analysis_1990_sem_veg_intraurb,slum_analysis_1990_veg_intra_urb,slum_analysis_1991_agua,slum_analysis_1991_area_favela,slum_analysis_1991_decliv_10,slum_analysis_1991_decliv_20,slum_analysis_1991_decliv_30,slum_analysis_1991_decliv_mais_30,slum_analysis_1991_frag_veg,slum_analysis_1991_hand_acima_6,slum_analysis_1991_hand_ate_3,slum_analysis_1991_hand_ate_6,slum_analysis_1991_risco,slum_analysis_1991_sem_risco,slum_analysis_1991_sem_veg_intraurb,slum_analysis_1991_veg_intra_urb,slum_analysis_1992_agua,slum_analysis_1992_area_favela,slum_analysis_1992_decliv_10,slum_analysis_1992_decliv_20,slum_analysis_1992_decliv_30,slum_analysis_1992_decliv_mais_30,slum_analysis_1992_frag_veg,slum_analysis_1992_hand_acima_6,slum_analysis_1992_hand_ate_3,slum_analysis_1992_hand_ate_6,slum_analysis_1992_risco,slum_analysis_1992_sem_risco,slum_analysis_1992_sem_veg_intraurb,slum_analysis_1992_veg_intra_urb,slum_analysis_1993_agua,slum_analysis_1993_area_favela,slum_analysis_1993_decliv_10,slum_analysis_1993_decliv_20,slum_analysis_1993_decliv_30,slum_analysis_1993_decliv_mais_30,slum_analysis_1993_frag_veg,slum_analysis_1993_hand_acima_6,slum_analysis_1993_hand_ate_3,slum_analysis_1993_hand_ate_6,slum_analysis_1993_risco,slum_analysis_1993_sem_risco,slum_analysis_1993_sem_veg_intraurb,slum_analysis_1993_veg_intra_urb,slum_analysis_1994_agua,slum_analysis_1994_area_favela,slum_analysis_1994_decliv_10,slum_analysis_1994_decliv_20,slum_analysis_1994_decliv_30,slum_analysis_1994_decliv_mais_30,slum_analysis_1994_frag_veg,slum_analysis_1994_hand_acima_6,slum_analysis_1994_hand_ate_3,slum_analysis_1994_hand_ate_6,slum_analysis_1994_risco,slum_analysis_1994_sem_risco,slum_analysis_1994_sem_veg_intraurb,slum_analysis_1994_veg_intra_urb,slum_analysis_1995_agua,slum_analysis_1995_area_favela,slum_analysis_1995_decliv_10,slum_analysis_1995_decliv_20,slum_analysis_1995_decliv_30,slum_analysis_1995_decliv_mais_30,slum_analysis_1995_frag_veg,slum_analysis_1995_hand_acima_6,slum_analysis_1995_hand_ate_3,slum_analysis_1995_hand_ate_6,slum_analysis_1995_risco,slum_analysis_1995_sem_risco,slum_analysis_1995_sem_veg_intraurb,slum_analysis_1995_veg_intra_urb,slum_analysis_1996_agua,slum_analysis_1996_area_favela,slum_analysis_1996_decliv_10,slum_analysis_1996_decliv_20,slum_analysis_1996_decliv_30,slum_analysis_1996_decliv_mais_30,slum_analysis_1996_frag_veg,slum_analysis_1996_hand_acima_6,slum_analysis_1996_hand_ate_3,slum_analysis_1996_hand_ate_6,slum_analysis_1996_risco,slum_analysis_1996_sem_risco,slum_analysis_1996_sem_veg_intraurb,slum_analysis_1996_veg_intra_urb,slum_analysis_1997_agua,slum_analysis_1997_area_favela,slum_analysis_1997_decliv_10,slum_analysis_1997_decliv_20,slum_analysis_1997_decliv_30,slum_analysis_1997_decliv_mais_30,slum_analysis_1997_frag_veg,slum_analysis_1997_hand_acima_6,slum_analysis_1997_hand_ate_3,slum_analysis_1997_hand_ate_6,slum_analysis_1997_risco,slum_analysis_1997_sem_risco,slum_analysis_1997_sem_veg_intraurb,slum_analysis_1997_veg_intra_urb,slum_analysis_1998_agua,slum_analysis_1998_area_favela,slum_analysis_1998_decliv_10,slum_analysis_1998_decliv_20,slum_analysis_1998_decliv_30,slum_analysis_1998_decliv_mais_30,slum_analysis_1998_frag_veg,slum_analysis_1998_hand_acima_6,slum_analysis_1998_hand_ate_3,slum_analysis_1998_hand_ate_6,slum_analysis_1998_risco,slum_analysis_1998_sem_risco,slum_analysis_1998_sem_veg_intraurb,slum_analysis_1998_veg_intra_urb,slum_analysis_1999_agua,slum_analysis_1999_area_favela,slum_analysis_1999_decliv_10,slum_analysis_1999_decliv_20,slum_analysis_1999_decliv_30,slum_analysis_1999_decliv_mais_30,slum_analysis_1999_frag_veg,slum_analysis_1999_hand_acima_6,slum_analysis_1999_hand_ate_3,slum_analysis_1999_hand_ate_6,slum_analysis_1999_risco,slum_analysis_1999_sem_risco,slum_analysis_1999_sem_veg_intraurb,slum_analysis_1999_veg_intra_urb,slum_analysis_2000_agua,slum_analysis_2000_area_favela,slum_analysis_2000_decliv_10,slum_analysis_2000_decliv_20,slum_analysis_2000_decliv_30,slum_analysis_2000_decliv_mais_30,slum_analysis_2000_frag_veg,slum_analysis_2000_hand_acima_6,slum_analysis_2000_hand_ate_3,slum_analysis_2000_hand_ate_6,slum_analysis_2000_risco,slum_analysis_2000_sem_risco,slum_analysis_2000_sem_veg_intraurb,slum_analysis_2000_veg_intra_urb,slum_analysis_2001_agua,slum_analysis_2001_area_favela,slum_analysis_2001_decliv_10,slum_analysis_2001_decliv_20,slum_analysis_2001_decliv_30,slum_analysis_2001_decliv_mais_30,slum_analysis_2001_frag_veg,slum_analysis_2001_hand_acima_6,slum_analysis_2001_hand_ate_3,slum_analysis_2001_hand_ate_6,slum_analysis_2001_risco,slum_analysis_2001_sem_risco,slum_analysis_2001_sem_veg_intraurb,slum_analysis_2001_veg_intra_urb,slum_analysis_2002_agua,slum_analysis_2002_area_favela,slum_analysis_2002_decliv_10,slum_analysis_2002_decliv_20,slum_analysis_2002_decliv_30,slum_analysis_2002_decliv_mais_30,slum_analysis_2002_frag_veg,slum_analysis_2002_hand_acima_6,slum_analysis_2002_hand_ate_3,slum_analysis_2002_hand_ate_6,slum_analysis_2002_risco,slum_analysis_2002_sem_risco,slum_analysis_2002_sem_veg_intraurb,slum_analysis_2002_veg_intra_urb,slum_analysis_2003_agua,slum_analysis_2003_area_favela,slum_analysis_2003_decliv_10,slum_analysis_2003_decliv_20,slum_analysis_2003_decliv_30,slum_analysis_2003_decliv_mais_30,slum_analysis_2003_frag_veg,slum_analysis_2003_hand_acima_6,slum_analysis_2003_hand_ate_3,slum_analysis_2003_hand_ate_6,slum_analysis_2003_risco,slum_analysis_2003_sem_risco,slum_analysis_2003_sem_veg_intraurb,slum_analysis_2003_veg_intra_urb,slum_analysis_2004_agua,slum_analysis_2004_area_favela,slum_analysis_2004_decliv_10,slum_analysis_2004_decliv_20,slum_analysis_2004_decliv_30,slum_analysis_2004_decliv_mais_30,slum_analysis_2004_frag_veg,slum_analysis_2004_hand_acima_6,slum_analysis_2004_hand_ate_3,slum_analysis_2004_hand_ate_6,slum_analysis_2004_risco,slum_analysis_2004_sem_risco,slum_analysis_2004_sem_veg_intraurb,slum_analysis_2004_veg_intra_urb,slum_analysis_2005_agua,slum_analysis_2005_area_favela,slum_analysis_2005_decliv_10,slum_analysis_2005_decliv_20,slum_analysis_2005_decliv_30,slum_analysis_2005_decliv_mais_30,slum_analysis_2005_frag_veg,slum_analysis_2005_hand_acima_6,slum_analysis_2005_hand_ate_3,slum_analysis_2005_hand_ate_6,slum_analysis_2005_risco,slum_analysis_2005_sem_risco,slum_analysis_2005_sem_veg_intraurb,slum_analysis_2005_veg_intra_urb,slum_analysis_2006_agua,slum_analysis_2006_area_favela,slum_analysis_2006_decliv_10,slum_analysis_2006_decliv_20,slum_analysis_2006_decliv_30,slum_analysis_2006_decliv_mais_30,slum_analysis_2006_frag_veg,slum_analysis_2006_hand_acima_6,slum_analysis_2006_hand_ate_3,slum_analysis_2006_hand_ate_6,slum_analysis_2006_risco,slum_analysis_2006_sem_risco,slum_analysis_2006_sem_veg_intraurb,slum_analysis_2006_veg_intra_urb,slum_analysis_2007_agua,slum_analysis_2007_area_favela,slum_analysis_2007_decliv_10,slum_analysis_2007_decliv_20,slum_analysis_2007_decliv_30,slum_analysis_2007_decliv_mais_30,slum_analysis_2007_frag_veg,slum_analysis_2007_hand_acima_6,slum_analysis_2007_hand_ate_3,slum_analysis_2007_hand_ate_6,slum_analysis_2007_risco,slum_analysis_2007_sem_risco,slum_analysis_2007_sem_veg_intraurb,slum_analysis_2007_veg_intra_urb,slum_analysis_2008_agua,slum_analysis_2008_area_favela,slum_analysis_2008_decliv_10,slum_analysis_2008_decliv_20,slum_analysis_2008_decliv_30,slum_analysis_2008_decliv_mais_30,slum_analysis_2008_frag_veg,slum_analysis_2008_hand_acima_6,slum_analysis_2008_hand_ate_3,slum_analysis_2008_hand_ate_6,slum_analysis_2008_risco,slum_analysis_2008_sem_risco,slum_analysis_2008_sem_veg_intraurb,slum_analysis_2008_veg_intra_urb,slum_analysis_2009_agua,slum_analysis_2009_area_favela,slum_analysis_2009_decliv_10,slum_analysis_2009_decliv_20,slum_analysis_2009_decliv_30,slum_analysis_2009_decliv_mais_30,slum_analysis_2009_frag_veg,slum_analysis_2009_hand_acima_6,slum_analysis_2009_hand_ate_3,slum_analysis_2009_hand_ate_6,slum_analysis_2009_risco,slum_analysis_2009_sem_risco,slum_analysis_2009_sem_veg_intraurb,slum_analysis_2009_veg_intra_urb,slum_analysis_2010_agua,slum_analysis_2010_area_favela,slum_analysis_2010_decliv_10,slum_analysis_2010_decliv_20,slum_analysis_2010_decliv_30,slum_analysis_2010_decliv_mais_30,slum_analysis_2010_frag_veg,slum_analysis_2010_hand_acima_6,slum_analysis_2010_hand_ate_3,slum_analysis_2010_hand_ate_6,slum_analysis_2010_risco,slum_analysis_2010_sem_risco,slum_analysis_2010_sem_veg_intraurb,slum_analysis_2010_veg_intra_urb,slum_analysis_2011_agua,slum_analysis_2011_area_favela,slum_analysis_2011_decliv_10,slum_analysis_2011_decliv_20,slum_analysis_2011_decliv_30,slum_analysis_2011_decliv_mais_30,slum_analysis_2011_frag_veg,slum_analysis_2011_hand_acima_6,slum_analysis_2011_hand_ate_3,slum_analysis_2011_hand_ate_6,slum_analysis_2011_risco,slum_analysis_2011_sem_risco,slum_analysis_2011_sem_veg_intraurb,slum_analysis_2011_veg_intra_urb,slum_analysis_2012_agua,slum_analysis_2012_area_favela,slum_analysis_2012_decliv_10,slum_analysis_2012_decliv_20,slum_analysis_2012_decliv_30,slum_analysis_2012_decliv_mais_30,slum_analysis_2012_frag_veg,slum_analysis_2012_hand_acima_6,slum_analysis_2012_hand_ate_3,slum_analysis_2012_hand_ate_6,slum_analysis_2012_risco,slum_analysis_2012_sem_risco,slum_analysis_2012_sem_veg_intraurb,slum_analysis_2012_veg_intra_urb,slum_analysis_2013_agua,slum_analysis_2013_area_favela,slum_analysis_2013_decliv_10,slum_analysis_2013_decliv_20,slum_analysis_2013_decliv_30,slum_analysis_2013_decliv_mais_30,slum_analysis_2013_frag_veg,slum_analysis_2013_hand_acima_6,slum_analysis_2013_hand_ate_3,slum_analysis_2013_hand_ate_6,slum_analysis_2013_risco,slum_analysis_2013_sem_risco,slum_analysis_2013_sem_veg_intraurb,slum_analysis_2013_veg_intra_urb,slum_analysis_2014_agua,slum_analysis_2014_area_favela,slum_analysis_2014_decliv_10,slum_analysis_2014_decliv_20,slum_analysis_2014_decliv_30,slum_analysis_2014_decliv_mais_30,slum_analysis_2014_frag_veg,slum_analysis_2014_hand_acima_6,slum_analysis_2014_hand_ate_3,slum_analysis_2014_hand_ate_6,slum_analysis_2014_risco,slum_analysis_2014_sem_risco,slum_analysis_2014_sem_veg_intraurb,slum_analysis_2014_veg_intra_urb,slum_analysis_2015_agua,slum_analysis_2015_area_favela,slum_analysis_2015_decliv_10,slum_analysis_2015_decliv_20,slum_analysis_2015_decliv_30,slum_analysis_2015_decliv_mais_30,slum_analysis_2015_frag_veg,slum_analysis_2015_hand_acima_6,slum_analysis_2015_hand_ate_3,slum_analysis_2015_hand_ate_6,slum_analysis_2015_risco,slum_analysis_2015_sem_risco,slum_analysis_2015_sem_veg_intraurb,slum_analysis_2015_veg_intra_urb,slum_analysis_2016_agua,slum_analysis_2016_area_favela,slum_analysis_2016_decliv_10,slum_analysis_2016_decliv_20,slum_analysis_2016_decliv_30,slum_analysis_2016_decliv_mais_30,slum_analysis_2016_frag_veg,slum_analysis_2016_hand_acima_6,slum_analysis_2016_hand_ate_3,slum_analysis_2016_hand_ate_6,slum_analysis_2016_risco,slum_analysis_2016_sem_risco,slum_analysis_2016_sem_veg_intraurb,slum_analysis_2016_veg_intra_urb,slum_analysis_2017_agua,slum_analysis_2017_area_favela,slum_analysis_2017_decliv_10,slum_analysis_2017_decliv_20,slum_analysis_2017_decliv_30,slum_analysis_2017_decliv_mais_30,slum_analysis_2017_frag_veg,slum_analysis_2017_hand_acima_6,slum_analysis_2017_hand_ate_3,slum_analysis_2017_hand_ate_6,slum_analysis_2017_risco,slum_analysis_2017_sem_risco,slum_analysis_2017_sem_veg_intraurb,slum_analysis_2017_veg_intra_urb,slum_analysis_2018_agua,slum_analysis_2018_area_favela,slum_analysis_2018_decliv_10,slum_analysis_2018_decliv_20,slum_analysis_2018_decliv_30,slum_analysis_2018_decliv_mais_30,slum_analysis_2018_frag_veg,slum_analysis_2018_hand_acima_6,slum_analysis_2018_hand_ate_3,slum_analysis_2018_hand_ate_6,slum_analysis_2018_risco,slum_analysis_2018_sem_risco,slum_analysis_2018_sem_veg_intraurb,slum_analysis_2018_veg_intra_urb,slum_analysis_2019_agua,slum_analysis_2019_area_favela,slum_analysis_2019_decliv_10,slum_analysis_2019_decliv_20,slum_analysis_2019_decliv_30,slum_analysis_2019_decliv_mais_30,slum_analysis_2019_frag_veg,slum_analysis_2019_hand_acima_6,slum_analysis_2019_hand_ate_3,slum_analysis_2019_hand_ate_6,slum_analysis_2019_risco,slum_analysis_2019_sem_risco,slum_analysis_2019_sem_veg_intraurb,slum_analysis_2019_veg_intra_urb,slum_analysis_2020_agua,slum_analysis_2020_area_favela,slum_analysis_2020_decliv_10,slum_analysis_2020_decliv_20,slum_analysis_2020_decliv_30,slum_analysis_2020_decliv_mais_30,slum_analysis_2020_frag_veg,slum_analysis_2020_hand_acima_6,slum_analysis_2020_hand_ate_3,slum_analysis_2020_hand_ate_6,slum_analysis_2020_risco,slum_analysis_2020_sem_risco,slum_analysis_2020_sem_veg_intraurb,slum_analysis_2020_veg_intra_urb,slum_analysis_2021_agua,slum_analysis_2021_area_favela,slum_analysis_2021_decliv_10,slum_analysis_2021_decliv_20,slum_analysis_2021_decliv_30,slum_analysis_2021_decliv_mais_30,slum_analysis_2021_frag_veg,slum_analysis_2021_hand_acima_6,slum_analysis_2021_hand_ate_3,slum_analysis_2021_hand_ate_6,slum_analysis_2021_risco,slum_analysis_2021_sem_risco,slum_analysis_2021_sem_veg_intraurb,slum_analysis_2021_veg_intra_urb,slum_analysis_2022_agua,slum_analysis_2022_area_favela,slum_analysis_2022_decliv_10,slum_analysis_2022_decliv_20,slum_analysis_2022_decliv_30,slum_analysis_2022_decliv_mais_30,slum_analysis_2022_frag_veg,slum_analysis_2022_hand_acima_6,slum_analysis_2022_hand_ate_3,slum_analysis_2022_hand_ate_6,slum_analysis_2022_risco,slum_analysis_2022_sem_risco,slum_analysis_2022_sem_veg_intraurb,slum_analysis_2022_veg_intra_urb,slum_analysis_2023_agua,slum_analysis_2023_area_favela,slum_analysis_2023_decliv_10,slum_analysis_2023_decliv_20,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb,.geo
4,000000000000000020bc,11001060006,1100106,11,Triângulo Novo - Guajará-Mirim (RO),Triângulo Novo,Guajará-Mirim,Rondônia,RO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-65.3471583..."

In [9]:
# nulls to csv
nulls.to_csv('./dataset/null_areas.csv')

In [ ]:
# find in list
filtered2[filtered2['cd_fcu'].isin(nulls['cd_fcu'])]

In [6]:
fcu['cd_fcu'] = fcu['cd_fcu'].astype(int)

In [7]:
join = pd.merge(fcu, filtered, on='cd_fcu', how='left')
join

,cd_fcu,nm_fcu,cd_uf,nm_uf,sigla_uf,cd_mun,nm_mun,geometry,slum_analysis_2023_agua,slum_analysis_2023_area_favela,slum_analysis_2023_decliv_10,slum_analysis_2023_decliv_20,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-46.37112 -23.5, -46.37141 -23.5001,...",0.0,25691.283136,13093.706021,12597.577115,0.000000,0.000000,0.000000,9140.496625,9623.741842,6927.044669,0.000000,25691.283136,25691.283136,0.000000
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-49.05007 -26.93529, -49.05009 -26.9...",0.0,23439.688164,28.206357,2294.131295,2961.689525,18155.660988,0.000000,20816.485204,1087.512547,1535.690413,23439.688164,0.000000,22552.742543,886.945621
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.48263 -22.8887, -43.48252 -22.88...",0.0,27767.177933,26996.941352,770.236580,0.000000,0.000000,0.000000,0.000000,25178.152383,2589.025550,0.000000,27767.177933,27767.177933,0.000000
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.21664 -22.87497, -43.21662 -22.8...",0.0,16089.096383,15357.627102,731.469281,0.000000,0.000000,0.000000,7376.189045,1799.550994,6913.356344,0.000000,16089.096383,16089.096383,0.000000
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-47.01387 -22.91975, -47.01458 -22.9...",0.0,28350.296100,825.077209,12395.549522,15129.669368,0.000000,0.000000,26716.313382,0.000000,1633.982717,21963.258028,6387.038072,28033.210066,317.086033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-35.76558 -9.57082, -35.76767 -9.572...",0.0,30214.851916,29332.995592,881.856323,0.000000,0.000000,0.000000,2742.399581,14396.759606,13075.692729,0.000000,30214.851916,30214.851916,0.000000
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-37.08826 -10.94031, -37.08824 -10.9...",0.0,18809.574907,13864.388486,4945.186422,0.000000,0.000000,0.000000,8688.501713,4500.925278,5620.147917,3447.156105,15362.418802,17531.959121,1277.615787
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-46.39452 -23.37916, -46.3949 -23.37...",0.0,20709.379994,7081.539203,11160.891328,2466.949463,0.000000,0.000000,11344.699639,6617.194222,2747.486134,0.000000,20709.379994,20709.379994,0.000000
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.95091 -8.04458, -34.95088 -8.044...",0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-37.34702 -5.14423, -37.34723 -5.145...",0.0,309283.943016,256729.030927,45431.147319,6233.294312,890.470459,40081.018466,101704.966950,144101.282858,63477.693207,0.000000,309283.943016,243152.414463,26050.510087

In [8]:
final = gpd.GeoDataFrame(join)
final

,cd_fcu,nm_fcu,cd_uf,nm_uf,sigla_uf,cd_mun,nm_mun,geometry,slum_analysis_2023_agua,slum_analysis_2023_area_favela,slum_analysis_2023_decliv_10,slum_analysis_2023_decliv_20,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-46.37112 -23.5, -46.37141 -23.5001,...",0.0,25691.283136,13093.706021,12597.577115,0.000000,0.000000,0.000000,9140.496625,9623.741842,6927.044669,0.000000,25691.283136,25691.283136,0.000000
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-49.05007 -26.93529, -49.05009 -26.9...",0.0,23439.688164,28.206357,2294.131295,2961.689525,18155.660988,0.000000,20816.485204,1087.512547,1535.690413,23439.688164,0.000000,22552.742543,886.945621
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.48263 -22.8887, -43.48252 -22.88...",0.0,27767.177933,26996.941352,770.236580,0.000000,0.000000,0.000000,0.000000,25178.152383,2589.025550,0.000000,27767.177933,27767.177933,0.000000
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.21664 -22.87497, -43.21662 -22.8...",0.0,16089.096383,15357.627102,731.469281,0.000000,0.000000,0.000000,7376.189045,1799.550994,6913.356344,0.000000,16089.096383,16089.096383,0.000000
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-47.01387 -22.91975, -47.01458 -22.9...",0.0,28350.296100,825.077209,12395.549522,15129.669368,0.000000,0.000000,26716.313382,0.000000,1633.982717,21963.258028,6387.038072,28033.210066,317.086033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-35.76558 -9.57082, -35.76767 -9.572...",0.0,30214.851916,29332.995592,881.856323,0.000000,0.000000,0.000000,2742.399581,14396.759606,13075.692729,0.000000,30214.851916,30214.851916,0.000000
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-37.08826 -10.94031, -37.08824 -10.9...",0.0,18809.574907,13864.388486,4945.186422,0.000000,0.000000,0.000000,8688.501713,4500.925278,5620.147917,3447.156105,15362.418802,17531.959121,1277.615787
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-46.39452 -23.37916, -46.3949 -23.37...",0.0,20709.379994,7081.539203,11160.891328,2466.949463,0.000000,0.000000,11344.699639,6617.194222,2747.486134,0.000000,20709.379994,20709.379994,0.000000
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.95091 -8.04458, -34.95088 -8.044...",0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-37.34702 -5.14423, -37.34723 -5.145...",0.0,309283.943016,256729.030927,45431.147319,6233.294312,890.470459,40081.018466,101704.966950,144101.282858,63477.693207,0.000000,309283.943016,243152.414463,26050.510087

In [10]:
final.columns = final.columns.str.replace('slum_analysis_2023_', '')
final

,cd_fcu,nm_fcu,cd_uf,nm_uf,sigla_uf,cd_mun,nm_mun,geometry,agua,area_favela,decliv_10,decliv_20,decliv_30,decliv_mais_30,frag_veg,hand_acima_6,hand_ate_3,hand_ate_6,risco,sem_risco,sem_veg_intraurb,veg_intra_urb
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-46.37112 -23.5, -46.37141 -23.5001,...",0.0,25691.283136,13093.706021,12597.577115,0.000000,0.000000,0.000000,9140.496625,9623.741842,6927.044669,0.000000,25691.283136,25691.283136,0.000000
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-49.05007 -26.93529, -49.05009 -26.9...",0.0,23439.688164,28.206357,2294.131295,2961.689525,18155.660988,0.000000,20816.485204,1087.512547,1535.690413,23439.688164,0.000000,22552.742543,886.945621
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.48263 -22.8887, -43.48252 -22.88...",0.0,27767.177933,26996.941352,770.236580,0.000000,0.000000,0.000000,0.000000,25178.152383,2589.025550,0.000000,27767.177933,27767.177933,0.000000
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.21664 -22.87497, -43.21662 -22.8...",0.0,16089.096383,15357.627102,731.469281,0.000000,0.000000,0.000000,7376.189045,1799.550994,6913.356344,0.000000,16089.096383,16089.096383,0.000000
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-47.01387 -22.91975, -47.01458 -22.9...",0.0,28350.296100,825.077209,12395.549522,15129.669368,0.000000,0.000000,26716.313382,0.000000,1633.982717,21963.258028,6387.038072,28033.210066,317.086033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-35.76558 -9.57082, -35.76767 -9.572...",0.0,30214.851916,29332.995592,881.856323,0.000000,0.000000,0.000000,2742.399581,14396.759606,13075.692729,0.000000,30214.851916,30214.851916,0.000000
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-37.08826 -10.94031, -37.08824 -10.9...",0.0,18809.574907,13864.388486,4945.186422,0.000000,0.000000,0.000000,8688.501713,4500.925278,5620.147917,3447.156105,15362.418802,17531.959121,1277.615787
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-46.39452 -23.37916, -46.3949 -23.37...",0.0,20709.379994,7081.539203,11160.891328,2466.949463,0.000000,0.000000,11344.699639,6617.194222,2747.486134,0.000000,20709.379994,20709.379994,0.000000
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.95091 -8.04458, -34.95088 -8.044...",0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-37.34702 -5.14423, -37.34723 -5.145...",0.0,309283.943016,256729.030927,45431.147319,6233.294312,890.470459,40081.018466,101704.966950,144101.282858,63477.693207,0.000000,309283.943016,243152.414463,26050.510087

In [11]:
final.to_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/Mapbiomas/mapbiomas_2023.shp')

/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_82355/220201384.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  final.to_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/Mapbiomas/mapbiomas_2023.shp')
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'area_favela' to 'area_favel'
  ogr_write(
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'decliv_mais_30' to 'decliv_mai'
  ogr_write(
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hand_acima_6' to 'hand_acima'
  ogr_write(
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'sem_veg_intraurb' to 'sem_veg_in'
  ogr_write(
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'veg_intra_urb' to 'veg_intra_'
  ogr_write(

In [23]:
final[final['slum_analysis_2023_area_favela'] == 0]

,cd_fcu,nm_fcu,cd_uf,nm_uf,sigla_uf,cd_mun,nm_mun,geometry,slum_analysis_2023_agua,slum_analysis_2023_area_favela,...,slum_analysis_2023_decliv_30,slum_analysis_2023_decliv_mais_30,slum_analysis_2023_frag_veg,slum_analysis_2023_hand_acima_6,slum_analysis_2023_hand_ate_3,slum_analysis_2023_hand_ate_6,slum_analysis_2023_risco,slum_analysis_2023_sem_risco,slum_analysis_2023_sem_veg_intraurb,slum_analysis_2023_veg_intra_urb
8,35503082222,Avenida Arraias do Araguaia,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-46.50383 -23.58049, -46.50361 -23.5...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,29057010017,Rio Bandeira,29,Bahia,BA,2905701,Camaçari,"POLYGON ((-38.33991 -12.69518, -38.33999 -12.6...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,33045571199,Estrada da Pedra V,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.65475 -22.97259, -43.65468 -22.9...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,35104010005,Santa Rita do Trevo,35,São Paulo,SP,3510401,Capivari,"POLYGON ((-47.39498 -22.99176, -47.39478 -22.9...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80,26116060825,Estr. Macacos - Av. Assis Chateaubriand,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.94063 -7.99351, -34.94059 -7.993...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12283,15022020021,Mutirão,15,Pará,PA,1502202,Capanema,"POLYGON ((-47.16351 -1.19206, -47.16346 -1.192...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12294,42054070067,Morro do Balão,42,Santa Catarina,SC,4205407,Florianópolis,"POLYGON ((-48.49567 -27.541, -48.49595 -27.541...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12327,33045571203,Jesuítas,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-43.66642 -22.8868, -43.6662 -22.886...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12333,26029020067,Garapu Final,26,Pernambuco,PE,2602902,Cabo de Santo Agostinho,"POLYGON ((-35.00956 -8.28345, -35.01005 -8.283...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-34.95091 -8.04458, -34.95088 -8.044...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# gdf.to_file('/Users/joaopedro/workspace/doutorado/DATASET/mapbiomas/Slum_Band_Areas_20232.shp')
# FeatureError: Could not add feature to layer at index 349: Attempt to write non-polygon (LINESTRING) geometry to POLYGON type shapefile.

# filter rows that geometry is not a polygon
# gdf2 = gdf[gdf['geometry'].apply(lambda x: x.geom_type == 'Polygon' or x.geom_type == 'MultiPolygon')]
# gdf2.to_file('/Users/joaopedro/workspace/doutorado/DATASET/mapbiomas/Slum_Band_Areas_2023.shp')