In [16]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.15f' % x)  # Exibe 5 casas decimais

In [17]:
gdf = gpd.read_file('../../dataset/shp/clusters.shp')

In [18]:
fcu = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/poligonos/fcu_blank/qg_2022_670_fcu_agreg.shp', )
fcu.columns = ['CD_FCU', 'NM_FCU', 'CD_UF', 'NM_UF', 'SIGLA_UF', 'CD_MUN', 'NM_MUN', 'geometry']
fcu['CD_FCU'] = fcu['CD_FCU'].astype(int)
fcu['CD_MUN'] = fcu['CD_MUN'].astype(int)

In [19]:
mun = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/BR_Localidades_2010_v1/BR_Localidades_2010_v1.shp')
mun = mun[mun['NM_CATEGOR'] == 'CIDADE']
mun['CD_GEOCODM'] = mun['CD_GEOCODM'].astype(int)

In [20]:
# for in fcu, get the centroid, the mun centroid and the distance between them
fcu = fcu.to_crs(epsg=3857)
mun = mun.to_crs(epsg=3857)
fcu['distance'] = 0

for index, row in fcu.iterrows():
    centroid = row.geometry.centroid
    # print(centroid)
    mun_geom = mun[mun['CD_GEOCODM'] == row['CD_MUN']]
    mun_centroid = mun_geom.iloc[0].geometry.centroid
    # print(mun_centroid)
    distance = centroid.distance(mun_centroid)
    
    # set distance to row
    fcu.at[index, 'distance'] = distance

fcu['dist_km'] = fcu['distance'] / 1000
fcu["dist_norm"] = fcu.groupby("CD_MUN")["dist_km"].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)

/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_79767/4183837124.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '23646.846826038814' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  fcu.at[index, 'distance'] = distance

In [21]:
fcu[fcu['CD_MUN'] == 1100205]

,CD_FCU,NM_FCU,CD_UF,NM_UF,SIGLA_UF,CD_MUN,NM_MUN,geometry,distance,dist_km,dist_norm
19,11002050023,Teixeirão,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7105862.355 -976691.522, -7106092.8...",3368.922677269234555,3.368922677269234,0.029679010004813
608,11002050035,Costa e Silva,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7112756.159 -976369.308, -7112754.7...",8075.558640322721658,8.075558640322722,0.085715731351987
885,11002050002,Nova Esperança,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7109842.438 -975113.295, -7109818.5...",6416.604482886934420,6.416604482886934,0.065964394605804
1004,11002050010,Jardim Santana IV,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7103873.821 -979422.246, -7103865.4...",1429.616088787476201,1.429616088787476,0.006589826188907
1025,11002050022,São Sebastião III,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7114834.694 -976685.496, -7114792.0...",10162.643809704739397,10.162643809704740,0.110564351679234
...,...,...,...,...,...,...,...,...,...,...,...
10425,11002050055,Roque C,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7112076.487 -980871.563, -7112260.7...",6678.721253989412617,6.678721253989413,0.069085129792887
10728,11002050043,Cohab II,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7111043.442 -983394.267, -7111213.1...",5986.389942468080335,5.986389942468080,0.060842304750077
10946,11002050064,Jardim Santana I,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7103826.288 -977725.362, -7103817.3...",2828.325204839405615,2.828325204839405,0.023242712368595
11372,11002050065,Socialista III,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7104874.338 -979129.904, -7104879.9...",1115.285822806147053,1.115285822806147,0.002847442528041
11418,11002050069,São Francisco II,11,Rondônia,RO,1100205,Porto Velho,"POLYGON ((-7104526.454 -981482.518, -7104540.5...",1635.279937054357788,1.635279937054358,0.009038438711097

In [22]:
cities = gpd.read_file('/Volumes/ssd/Doutorado/DATASET/IBGE/BR_Municipios_2022/BR_Municipios_2022.shp')
cities = cities[['CD_MUN', 'AREA_KM2']]
cities['CD_MUN'] = cities['CD_MUN'].astype(int)
cities

       CD_MUN             AREA_KM2
0     1100015 7067.127000000000407
1     1100023 4426.570999999999913
2     1100031 1314.352000000000089
3     1100049 3793.000000000000000
4     1100056 2783.300000000000182
...       ...                  ...
5567  5222005  954.115000000000009
5568  5222054  733.793999999999983
5569  5222203 1052.593000000000075
5570  5222302 2181.592999999999847
5571  5300108 5760.783999999999651

[5572 rows x 2 columns]

In [23]:
join_data = fcu.merge(cities, on='CD_MUN', how='left')
join_data = join_data.merge(gdf.drop(columns=['geometry']), on='CD_FCU', how='left')
join_data

,CD_FCU,NM_FCU,CD_UF,NM_UF,SIGLA_UF,CD_MUN,NM_MUN,geometry,distance,dist_km,dist_norm,AREA_KM2,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pip,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk_area,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp,wtr_idx,sanit_idx,living_are,durable_ho,cluster_3
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-5162009.388 -2692597.734, -5162042....",23646.846826038814470,23.646846826038814,0.533158552343469,1521.201999999999998,2.956632653061225,44.020000000000003,29.000000000000000,99.000000000000000,92.890000000000001,32.609999999999999,17.340000000000000,0.000000000000000,50.039999999999999,0.000000000000000,0.000000000000000,0.593881394151810,100.000000000000000,0.000000000000000,0.318900000000000,0.002600000000000,0.000000000000000,0.678600000000000,0.000000000000000,0.000000000000000,0.206600000000000,0.000000000000000,0.030600000000000,0.000000000000000,0.000000000000000,0.762800000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.994900000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005100000000000,0.000000000000000,0.000000000000000,0.000000000000000,50.965558831959356,49.034441168040658,0.000000000000000,0.000000000000000,35.578202056669660,26.962626321230797,37.459171622099561,0.000226338812134,0.032435898459901,0.117353676384719,0.000138925792410,98.719999999999999,45062.209999999999127,884.615384615384642,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,752.192509434099634,2071.724078601533165,0.997450127493625,0.451028037383178,0.681207545029720,0.321535692861428,1.000000000000000
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-5460228.537 -3115389.701, -5460231....",2544.012189292799121,2.544012189292799,0.080353569412576,518.619000000000028,2.809917355371901,60.270000000000003,34.000000000000000,102.000000000000000,96.629999999999995,79.709999999999994,4.120000000000000,0.000000000000000,16.180000000000000,0.000000000000000,0.000000000000000,-1.339049333599375,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.958700000000000,0.000000000000000,0.033100000000000,0.000000000000000,0.008300000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,3.783948041683024,100.000000000000000,0.120335888401926,9.787379757137918,12.635362314477181,77.456922039982985,88.808712208672446,6.551667421570913,4.639620369756640,0.000128408715662,0.030195952437025,0.119900281982149,0.000063380103705,100.000000000000000,2916.000000000000000,8.547008547008547,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,886.945621266084572,281.660799669791857,1167.193154171149445,1.000000000000000,0.978808411214953,0.872972435449063,0.999800039992001,0.000000000000000
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4840464.531 -2618564.009, -4840451....",28454.700967727036186,28.454700967727035,0.507650945554618,1200.328999999999951,2.834532374100720,87.500000000000000,34.000000000000000,90.000000000000000,96.579999999999998,29.440000000000001,23.100000000000001,0.000000000000000,47.460000000000001,0.000000000000000,0.000000000000000,-0.810630944817607,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.226089801895839,2.773910198104173,0.000000000000000,0.000000000000000,0.000000000000000,9.324049985563214,90.675950014436765,0.000190146016394,0.034092435378463,0.117907963273184,0.000099145903547,100.000000000000000,14189.510000000000218,821.428571428571445,100.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1003.263291531211848,1.000000000000000,1.000000000000000,0.853670564587899,0.999800039992001,0.000000000000000
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4810854.603 -2616904.986, -4810851....",1286.545036119262932,1.286545036119263,0.018809137112925,1200.328999999999951,2.836461126005362,98.980000000000004,35.000000000000000,84.000000000000000,91.760000000000005,37.430000000000000,14.080000000000000,0.090000000000000,47.539999999999999,0.850000000000000,0.000000000000000,-1.517390653235870,100.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.847200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.002700000000000,0.144800000000000,0.005400000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.992000000000000,0.002700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,95.453633544999178,4.546366455000812,0.000000000000000,0.000000000000000,45.845887607786160,42.969202120337997,11.184910271875841,0.000173446921752,0.035576993041846,0.118095190761406,0.000125744957099,99.459999999999994,65726.529999999998836,2125.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,683.377208610892808,659.135305883393812,0.990750462476876,0.892920560747663,0.579645476589511,0.999999999999999,0.000000000000000
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-5233560.28 -2622317.23, -5233639.32...",5245.591377457038107,5.245591377457038,0.146824431092626,794.571000000000026,2.977375565610860,17.879999999999999,27.000000000000000,107.000000000000000,88.519999999999996,24.010000000000002,18.690000000000001,0.000000000000000,57.140000000000001,0.150000000000000,0.000000000000000,-0.248884424989380,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.570100000000000,0.000000000000000,0.009000000000000,0.000000000000000,0.031700000000000,0.389100000000000,0.000000000000000,0.000000000000000,0.995500000000000,0.004500000000000,0.000000000000000,0.000000000000000,0.991000000000000,0.000000000000000,0.009000000000000,0.991000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.009000000000000,0.000000000000000,1.118457571398694,77.471000482297413,2.910294857486170,43.722822077076380,53.366883065437442,0.000000000000000,94.236452727941781,5.763547272058226,0.000000000000000,0.000166720418881,0.032145364786926,0.117010048297412,0.000089746761517,100.000000000000000,17788.590000000000146,783.783783783783861,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,317.086033241421603,1383.163402628007816,1488.467146176819824,0.991000449977501,0.699696261682243,0.828075320854568,0.999800039992001,1.000000000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-3981406.076 -1070408.33, -3981639.1...",12464.347470914697624,12.464347470914698,0.490099152035993,509.319999999999993,3.095238095238095,16.460000000000001,27.000000000000000,104.000000000000000,88.359999999999999,25.640000000000001,8.890000000000001,0.340000000000000,64.620000000000005,0.510000000000000,0.000000000000000,4.283775096745155,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.026500000000000,0.000000000000000,0.015900000000000,0.957700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989400000000000,0.000000000000000,0.010600000000000,0.719600000000000,0.269800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.010600000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.081381283260754,2.918618716739250,0.000000000000000,0.000000000000000,9.076329708837251,43.275713431349082,47.647956859813675,0.000033033549837,0.032031551352307,0.118138291060697,0.000044508642802,6.350000000000000,19327.979999999999563,2700.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1523.970940459529402,2773.897971437058459,0.854507274636268,0.545140186915888,0.804361131811426,0.999800039992001,1.000000000000000
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-4128645.906 -1225338.301, -4128644....",5943.694057307008734,5.943694057307009,0.187357972810060,182.163000000000011,2.806722689075630,36.619999999999997,30.000000000000000,104.000000000000000,85.170000000000002,25.149999999999999,16.170000000000002,0.000000000000000,58.680000000000000,0.000000000000000,0.000000000000000,-1.065465941070793,100.000000000000000,0.000000000000000,0.958000000000000,0.042000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.075600000000000,0.050400000000000,0.117600000000000,0.000000000000000,0.000000000000000,0.756300000000000,0.000000000000000,0.000000000000000,0.974800000000000,0.025200000000000,0.000000000000000,0.000000000000000,0.966400000000000,0.016800000000000,0.016800000000000,0.983200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.016800000000000,0.000000000000000,6.792369275195012,18.326602923923836,73.709206900924869,26.290793099075096,0.000000000000000,0.000000000000000,46.191908936603625,29.879186236706872,23.928904826689482,0.000031736680244,0.032309882285635,0.117883362452482,0.000045378049870,100.000000000000000,17261.869999999998981,2000.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,1277.615786803002493,365.389491701098336,2430.944342087160749,0.974801259937003,0.385397196261682,0.844823527665766,0.999800039992001,1.000000000000000
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-5164614.754 -2677936.544, -5164656....",18639.788181369531230,18.639788181369532,0.949104660627787,318.675000000000011,3.196721311475410,20.899999999999999,24.000000000000000,103.000000000000000,96.480000000000004,30.260000000000002,14.100000000000000,0.000000000000000,55.640000000000001,0.000000000000000,0.000000000000000,0.619302742172345,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.008200000000000,0.000000000000000,0.991800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.565600000000000,0.278700000000000,0.155700000000000,0.844300000000000,0.155700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,34.194839273674610,53.892928377406491,11.912232348918900,0.000000000000000,54.780489043770409,13.266868126150957,31.952642830078627,0.000117513181764,0.031058578028131,0.117311225909030,0.000100366218354,100.000000000000000,3868.860000000000127,89.108910891089110,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1296.932330981916721,5287.866697468050006,0.704964751762412,0.532710280373832,0.804146435401226,0.999800039992001,2.000000000000000
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-3890716.958 -898474.936, -3890713.9...",7352.563602570774492,7.352563602570775,0.570651697479528,218.842999999999989,2.665343915343915,83.560000000000002,36.000000000000000,90.000000000000000,93.390000000000001,29.829999999999998,17.370000000000001,0.150000000000000,51.759999999999998,0.890000000000000,0.000000000000000,-0.196974020683646,99.879999999999995,0.120000000000000,0.928500000000000,0.014600000000000,0.054300000000000,0.001300000000000,0.000000000000000,0.001300000000000,0.429100000000000,0.161600000000000,0.166900000000000,0.121900000000000,0.038400000000000,0.079500000000000,0.002600000000000,0.000000000000000,0.998700000000000,0.001300000000000,0.000000000000000,0.000000000000000,0.973500000000000,0.023800000000000,0.002600000000000,0.887400000000000,0.080800000000000,0.030500000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.001300000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000029070225491,0.032954450738533,0.118833241983087,0.000048112787405,99.209999999999994,19323.349999999998545,961.538461538461547,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,486.490854788136858,811.613421159032669,0.930403479826009,0.704766355140187,0.848365107681029,0.997200559888022,1.000000000000000
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-4157451.583 -573424.392, -4157474.5...",5185.085296568466219,5.185085296568467,0.822095149119573,2099.333999999999833,2.872340425531915,95.709999999999994,37.000000000000000,101.000000000000000,86.569999999999993,47.649999999999999,11.850000000000000,0.250000000000000,39.259999999999998,0.990000000000000,0.000000000000000,-0.035416414208469,100.000000000000000,0.000000000000000,0.992900000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.007100000000000,0.737600000000000,0.056700000000000,0.177300000000000,0.000000000000000,0.014200000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.957400000000000,0.028400000000000,0.014200000000000,0.971600000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.014200000000000,0.000000000000000,21.382140924663187,0.000000000000000,83.007552355743059,14.689138684519843,2.015395384172193,0.287913575564858,32.884011358103550,20.524083012020675,46.591905629875733,0.000025993265931,0.034204725825526,0.119566760337126,0.000043055032728,92.200000000000003,581.679999999999950,81.896551724137936,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,26050.510087316175486,738.810280349707796,2648.432513307378031,0.964501774911254,0.491285046728972,0.872328257207228,0.999800039992002,1.000000000000000

In [24]:
tabela9887_2 = pd.read_excel('/Volumes/ssd/Doutorado/DATASET/IBGE/Favelas e Comunidades Urbanas - 2022/tabelas/População/9887/tabela9887_pop.xlsx', skiprows=4, skipfooter=1)
tabela9887_2.columns = ['CD_FCU', 'NM_FCU', 'pessoas']
join_data = join_data.merge(tabela9887_2, on='CD_FCU', how='left')
join_data

,CD_FCU,NM_FCU_x,CD_UF,NM_UF,SIGLA_UF,CD_MUN,NM_MUN,geometry,distance,dist_km,dist_norm,AREA_KM2,hh_density,age_index,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pip,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk_area,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp,wtr_idx,sanit_idx,living_are,durable_ho,cluster_3,NM_FCU_y,pessoas
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-5162009.388 -2692597.734, -5162042....",23646.846826038814470,23.646846826038814,0.533158552343469,1521.201999999999998,2.956632653061225,44.020000000000003,29.000000000000000,99.000000000000000,92.890000000000001,32.609999999999999,17.340000000000000,0.000000000000000,50.039999999999999,0.000000000000000,0.000000000000000,0.593881394151810,100.000000000000000,0.000000000000000,0.318900000000000,0.002600000000000,0.000000000000000,0.678600000000000,0.000000000000000,0.000000000000000,0.206600000000000,0.000000000000000,0.030600000000000,0.000000000000000,0.000000000000000,0.762800000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.994900000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005100000000000,0.000000000000000,0.000000000000000,0.000000000000000,50.965558831959356,49.034441168040658,0.000000000000000,0.000000000000000,35.578202056669660,26.962626321230797,37.459171622099561,0.000226338812134,0.032435898459901,0.117353676384719,0.000138925792410,98.719999999999999,45062.209999999999127,884.615384615384642,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,752.192509434099634,2071.724078601533165,0.997450127493625,0.451028037383178,0.681207545029720,0.321535692861428,1.000000000000000,Jardim Miliunas - São Paulo (SP),1159
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-5460228.537 -3115389.701, -5460231....",2544.012189292799121,2.544012189292799,0.080353569412576,518.619000000000028,2.809917355371901,60.270000000000003,34.000000000000000,102.000000000000000,96.629999999999995,79.709999999999994,4.120000000000000,0.000000000000000,16.180000000000000,0.000000000000000,0.000000000000000,-1.339049333599375,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.958700000000000,0.000000000000000,0.033100000000000,0.000000000000000,0.008300000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,3.783948041683024,100.000000000000000,0.120335888401926,9.787379757137918,12.635362314477181,77.456922039982985,88.808712208672446,6.551667421570913,4.639620369756640,0.000128408715662,0.030195952437025,0.119900281982149,0.000063380103705,100.000000000000000,2916.000000000000000,8.547008547008547,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,886.945621266084572,281.660799669791857,1167.193154171149445,1.000000000000000,0.978808411214953,0.872972435449063,0.999800039992001,0.000000000000000,Rua Araranguá - Blumenau (SC),340
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4840464.531 -2618564.009, -4840451....",28454.700967727036186,28.454700967727035,0.507650945554618,1200.328999999999951,2.834532374100720,87.500000000000000,34.000000000000000,90.000000000000000,96.579999999999998,29.440000000000001,23.100000000000001,0.000000000000000,47.460000000000001,0.000000000000000,0.000000000000000,-0.810630944817607,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.226089801895839,2.773910198104173,0.000000000000000,0.000000000000000,0.000000000000000,9.324049985563214,90.675950014436765,0.000190146016394,0.034092435378463,0.117907963273184,0.000099145903547,100.000000000000000,14189.510000000000218,821.428571428571445,100.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1003.263291531211848,1.000000000000000,1.000000000000000,0.853670564587899,0.999800039992001,0.000000000000000,Tiqui - Rio de Janeiro (RJ),394
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4810854.603 -2616904.986, -4810851....",1286.545036119262932,1.286545036119263,0.018809137112925,1200.328999999999951,2.836461126005362,98.980000000000004,35.000000000000000,84.000000000000000,91.760000000000005,37.430000000000000,14.080000000000000,0.090000000000000,47.539999999999999,0.850000000000000,0.000000000000000,-1.517390653235870,100.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.847200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.002700000000000,0.144800000000000,0.005400000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.992000000000000,0.002700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,95.453633544999178,4.546366455000812,0.000000000000000,0.000000000000000,45.845887607786160,42.969202120337997,11.184910271875841,0.000173446921752,0.035576993041846,0.118095190761406,0.000125744957099,99.459999999999994,65726.529999999998836,2125.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,683.377208610892808,659.135305883393812,0.990750462476876,0.892920560747663,0.579645476589511,0.999999999999999,0.000000000000000,Parque Nossa Senhora da Penha - Rio de Janeiro...,1058
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-5233560.28 -2622317.23, -5233639.32...",5245.591377457038107,5.245591377457038,0.146824431092626,794.571000000000026,2.977375565610860,17.879999999999999,27.000000000000000,107.000000000000000,88.519999999999996,24.010000000000002,18.690000000000001,0.000000000000000,57.140000000000001,0.150000000000000,0.000000000000000,-0.248884424989380,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.570100000000000,0.000000000000000,0.009000000000000,0.000000000000000,0.031700000000000,0.389100000000000,0.000000000000000,0.000000000000000,0.995500000000000,0.004500000000000,0.000000000000000,0.000000000000000,0.991000000000000,0.000000000000000,0.009000000000000,0.991000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.009000000000000,0.000000000000000,1.118457571398694,77.471000482297413,2.910294857486170,43.722822077076380,53.366883065437442,0.000000000000000,94.236452727941781,5.763547272058226,0.000000000000000,0.000166720418881,0.032145364786926,0.117010048297412,0.000089746761517,100.000000000000000,17788.590000000000146,783.783783783783861,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,317.086033241421603,1383.163402628007816,1488.467146176819824,0.991000449977501,0.699696261682243,0.828075320854568,0.999800039992001,1.000000000000000,Núcleo Residencial Jardim das Andorinhas II - ...,658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-3981406.076 -1070408.33, -3981639.1...",12464.347470914697624,12.464347470914698,0.490099152035993,509.319999999999993,3.095238095238095,16.460000000000001,27.000000000000000,104.000000000000000,88.359999999999999,25.640000000000001,8.890000000000001,0.340000000000000,64.620000000000005,0.510000000000000,0.000000000000000,4.283775096745155,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.026500000000000,0.000000000000000,0.015900000000000,0.957700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989400000000000,0.000000000000000,0.010600000000000,0.719600000000000,0.269800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.010600000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.081381283260754,2.918618716739250,0.000000000000000,0.000000000000000,9.076329708837251,43.275713431349082,47.647956859813675,0.000033033549837,0.032031551352307,0.118138291060697,0.000044508642802,6.350000000000000,19327.979999999999563,2700.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1523.970940459529402,2773.897971437058459,0.854507274636268,0.545140186915888,0.804361131811426,0.999800039992001,1.000000000000000,Vila Santa Cruz - Maceió (AL),585
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-4128645.906 -1225338.301, -4128644....",5943.694057307008734,5.943694057307009,0.187357972810060,182.163000000000011,2.806722689075630,36.619999999999997,30.000000000000000,104.000000000000000,85.170000000000002,25.149999999999999,16.170000000000002,0.000000000000000,58.680000000000000,0.000000000000000,0.000000000000000,-1.065465941070793,100.000000000000000,0.000000000000000,0.958000000000000,0.042000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.075600000000000,0.050400000000000,0.117600000000000,0.000000000000000,0.000000000000000,0.756300000000000,0.000000000000000,0.000000000000000,0.974800000000000,0.025200000000000,0.000000000000000,0.000000000000000,0.966400000000000,0.016800000000000,0.016800000000000,0.983200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.016800000000000,0.000000000000000,6.792369275195012,18.326602923923836,73.709206900924869,26.290793099075096,0.000000000000000,0.000000000000000,46.191908936603625,29.879186236706872,23.928904826689482,0.000031736680244,0.032309882285635,0.117883362452482,0.000045378049870,100.000000000000000,17261.869999999998981,2000.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,1277.615786803002493,365.389491701098336,2430.944342087160749,0.974801259937003,0.385397196261682,0.844823527665766,0.999800039992001,1.000000000000000,Invasão da Jabotiana - Aracaju (SE),334
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-5164614.754 -2677936.544, -5164656....",18639.788181369531230,18.639788181369532,0.949104660627787,318.675000000000011,3.196721311475410,20.899999999999999,24.000000000000000,103.000000000000000,96.480000000000004,30.260000000000002,14.100000000000000,0.000000000000000,55.640000000000001,0.000000000000000,0.000000000000000,0.619302742172345,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.008200000000000,0.000000000000000,0.991800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.565600000000000,0.278700000000000,0.155700000000000,0.844300000000000,0.155700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,34.194839273674610,53.892928377406491,11.912232348918900,0.000000000000000,54.780489043770409,13.266868126150957,31.952642830078627,0.000117513181764,0.031058578028131,0.117311225909030,0.000100366218354,100.000000000000000,3868.860000000000127,89.108910891089110,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1296.932330981916721,5287.866697468050006,0.704964751762412,0.532710280373832,0.804146435401226,0.999800039992001,2.000000000000000,Residencial Bambi II - Guarulhos (SP),390
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-3890716.958 -898474.936, -3890713.9...",7352.563602570774492,7.352563602570775,0.570651697479528,218.842999999999989,2.665343915343915,83.560000000000002,36.000000000000000,90.000000000000000,93.390000000000001,29.829999999999998,17.370000000000001,0.150000000000000,51.759999999999998,0.890000000000000,0.000000000000000,-0.196974020683646,99.879999999999995,0.120000000000000,0.928500000000000,0.014600000000000,0.054300000000000,0.001300000000000,0.000000000000000,0.001300000000000,0.429100000000000,0.161600000000000,0.166900000000000,0.121900000000000,0.038400000000000,0.079500000000000,0.002600000000000,0.000000000000000,0.998700000000000,0.001300000000000,0.000000000000000,0.000000000000000,0.973500000000000,0.023800000000000,0.002600000000000,0.887400000000000,0.080800000000000,0.030500000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.001300000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000029070225491,0.032954450738533,0.118833241983087,0.000048112787405,99.209999999999994,19323.349999999998545,961.538461538461547,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,486.490854788136858,811.613421159032669,0.930403479826009,0.704766355140187,0.848365107681029,0.997200559888022,1.000000000000000,Sítio Wanderley - Recife (PE),2015
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-4157451.583 -573424.392, -4157474.5...",5185.085296568466219,5.185085296568467,0.822095149119573,2099.333999999999833,2.872340425531915,95.709999999999994,37.000000000000000,101.000000000000000,86.569999999999993,47.649999999999999,11.850000000000000,0.250000000000000,39.259999999999998,0.990000000000000,0.000000000000000,-0.035416414208469,100.000000000000000,0.000000000000000,0.992900000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.007100000000000,0.737600000000000,0.056700000000000,0.177300000000000,0.000000000000000,0.014200000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.957400000000000,0.028400000000000,0.014200000000000,0.971600000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.014200000000000,0.000000000000000,21.382140924663187,0.000000000000000,83.007552355743059,14.689138684519843,2.015395384172193,0.287913575564858,32.884011358103550,20.524083012020675,46.591905629875733,0.000025993265931,0.034204725825526,0.119566760337126,0.000043055032728,92.200000000000003,581.679999999999950,81.896551724137936,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,26050.510087316175486,738.810280349707796,2648.432513307378031,0.964501774911254,0.491285046728972,0.872328257207228,0.999800039992002,1.000000000000000,Resistência - Mossoró (RN),405

In [25]:
join_data = join_data.drop(columns=['NM_FCU_y'])
join_data.columns =      ['CD_FCU', 'NM_FCU',   'CD_UF', 'NM_UF', 'SIGLA_UF', 'CD_MUN', 'NM_MUN', 'geometry', 'distance', 'dist_km', 'dist_norm', 'area',    'hh_density', 'age_idx', 'median_age', 'sex_ratio', 'literate', 'race_wht', 'race_blk', 'race_ylw', 'race_brn', 'race_ind', 'race_unk', 'depriv_idx', 'priv_hh', 'coll_hh', 'hh_type_1', 'hh_type_2', 'hh_type_3', 'hh_type_4', 'hh_type_5', 'hh_type_6', 'sanit_1', 'sanit_2', 'sanit_3', 'sanit_4', 'sanit_5', 'sanit_6', 'sanit_7', 'no_bath', 'excl_bath', 'shrd_bath', 'toilet', 'no_toilet', 'wtr_pipe', 'wtr_semi', 'no_wtr_pip', 'wtr_dist', 'wtr_deep', 'wtr_shal', 'wtr_spring', 'wtr_truck', 'wtr_rain', 'wtr_river', 'wtr_oth', 'wtr_area', 'veg_area', 'risk', 'slope_10', 'slope_20', 'slope_30', 'slope_30p', 'hand_6p', 'hand_3_6', 'hand_0_3', 'SO2', 'CO', 'O3', 'NO2', 'waste_coll', 'demo_dens', 'est_dens', 'est_edu', 'est_health', 'est_relig', 'est_agri', 'est_other', 'est_const', 'intra_veg', 'prim_hosp', 'inp_hosp', 'wtr_idx', 'sanit_idx', 'liv_a_idx', 'hh_idx', 'cluster', 'population']
join_data

,CD_FCU,NM_FCU,CD_UF,NM_UF,SIGLA_UF,CD_MUN,NM_MUN,geometry,distance,dist_km,dist_norm,area,hh_density,age_idx,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pip,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp,wtr_idx,sanit_idx,liv_a_idx,hh_idx,cluster,population
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-5162009.388 -2692597.734, -5162042....",23646.846826038814470,23.646846826038814,0.533158552343469,1521.201999999999998,2.956632653061225,44.020000000000003,29.000000000000000,99.000000000000000,92.890000000000001,32.609999999999999,17.340000000000000,0.000000000000000,50.039999999999999,0.000000000000000,0.000000000000000,0.593881394151810,100.000000000000000,0.000000000000000,0.318900000000000,0.002600000000000,0.000000000000000,0.678600000000000,0.000000000000000,0.000000000000000,0.206600000000000,0.000000000000000,0.030600000000000,0.000000000000000,0.000000000000000,0.762800000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.994900000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005100000000000,0.000000000000000,0.000000000000000,0.000000000000000,50.965558831959356,49.034441168040658,0.000000000000000,0.000000000000000,35.578202056669660,26.962626321230797,37.459171622099561,0.000226338812134,0.032435898459901,0.117353676384719,0.000138925792410,98.719999999999999,45062.209999999999127,884.615384615384642,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,752.192509434099634,2071.724078601533165,0.997450127493625,0.451028037383178,0.681207545029720,0.321535692861428,1.000000000000000,1159
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-5460228.537 -3115389.701, -5460231....",2544.012189292799121,2.544012189292799,0.080353569412576,518.619000000000028,2.809917355371901,60.270000000000003,34.000000000000000,102.000000000000000,96.629999999999995,79.709999999999994,4.120000000000000,0.000000000000000,16.180000000000000,0.000000000000000,0.000000000000000,-1.339049333599375,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.958700000000000,0.000000000000000,0.033100000000000,0.000000000000000,0.008300000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,3.783948041683024,100.000000000000000,0.120335888401926,9.787379757137918,12.635362314477181,77.456922039982985,88.808712208672446,6.551667421570913,4.639620369756640,0.000128408715662,0.030195952437025,0.119900281982149,0.000063380103705,100.000000000000000,2916.000000000000000,8.547008547008547,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,886.945621266084572,281.660799669791857,1167.193154171149445,1.000000000000000,0.978808411214953,0.872972435449063,0.999800039992001,0.000000000000000,340
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4840464.531 -2618564.009, -4840451....",28454.700967727036186,28.454700967727035,0.507650945554618,1200.328999999999951,2.834532374100720,87.500000000000000,34.000000000000000,90.000000000000000,96.579999999999998,29.440000000000001,23.100000000000001,0.000000000000000,47.460000000000001,0.000000000000000,0.000000000000000,-0.810630944817607,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.226089801895839,2.773910198104173,0.000000000000000,0.000000000000000,0.000000000000000,9.324049985563214,90.675950014436765,0.000190146016394,0.034092435378463,0.117907963273184,0.000099145903547,100.000000000000000,14189.510000000000218,821.428571428571445,100.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1003.263291531211848,1.000000000000000,1.000000000000000,0.853670564587899,0.999800039992001,0.000000000000000,394
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4810854.603 -2616904.986, -4810851....",1286.545036119262932,1.286545036119263,0.018809137112925,1200.328999999999951,2.836461126005362,98.980000000000004,35.000000000000000,84.000000000000000,91.760000000000005,37.430000000000000,14.080000000000000,0.090000000000000,47.539999999999999,0.850000000000000,0.000000000000000,-1.517390653235870,100.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.847200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.002700000000000,0.144800000000000,0.005400000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.992000000000000,0.002700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,95.453633544999178,4.546366455000812,0.000000000000000,0.000000000000000,45.845887607786160,42.969202120337997,11.184910271875841,0.000173446921752,0.035576993041846,0.118095190761406,0.000125744957099,99.459999999999994,65726.529999999998836,2125.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,683.377208610892808,659.135305883393812,0.990750462476876,0.892920560747663,0.579645476589511,0.999999999999999,0.000000000000000,1058
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-5233560.28 -2622317.23, -5233639.32...",5245.591377457038107,5.245591377457038,0.146824431092626,794.571000000000026,2.977375565610860,17.879999999999999,27.000000000000000,107.000000000000000,88.519999999999996,24.010000000000002,18.690000000000001,0.000000000000000,57.140000000000001,0.150000000000000,0.000000000000000,-0.248884424989380,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.570100000000000,0.000000000000000,0.009000000000000,0.000000000000000,0.031700000000000,0.389100000000000,0.000000000000000,0.000000000000000,0.995500000000000,0.004500000000000,0.000000000000000,0.000000000000000,0.991000000000000,0.000000000000000,0.009000000000000,0.991000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.009000000000000,0.000000000000000,1.118457571398694,77.471000482297413,2.910294857486170,43.722822077076380,53.366883065437442,0.000000000000000,94.236452727941781,5.763547272058226,0.000000000000000,0.000166720418881,0.032145364786926,0.117010048297412,0.000089746761517,100.000000000000000,17788.590000000000146,783.783783783783861,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,317.086033241421603,1383.163402628007816,1488.467146176819824,0.991000449977501,0.699696261682243,0.828075320854568,0.999800039992001,1.000000000000000,658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-3981406.076 -1070408.33, -3981639.1...",12464.347470914697624,12.464347470914698,0.490099152035993,509.319999999999993,3.095238095238095,16.460000000000001,27.000000000000000,104.000000000000000,88.359999999999999,25.640000000000001,8.890000000000001,0.340000000000000,64.620000000000005,0.510000000000000,0.000000000000000,4.283775096745155,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.026500000000000,0.000000000000000,0.015900000000000,0.957700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989400000000000,0.000000000000000,0.010600000000000,0.719600000000000,0.269800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.010600000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.081381283260754,2.918618716739250,0.000000000000000,0.000000000000000,9.076329708837251,43.275713431349082,47.647956859813675,0.000033033549837,0.032031551352307,0.118138291060697,0.000044508642802,6.350000000000000,19327.979999999999563,2700.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1523.970940459529402,2773.897971437058459,0.854507274636268,0.545140186915888,0.804361131811426,0.999800039992001,1.000000000000000,585
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-4128645.906 -1225338.301, -4128644....",5943.694057307008734,5.943694057307009,0.187357972810060,182.163000000000011,2.806722689075630,36.619999999999997,30.000000000000000,104.000000000000000,85.170000000000002,25.149999999999999,16.170000000000002,0.000000000000000,58.680000000000000,0.000000000000000,0.000000000000000,-1.065465941070793,100.000000000000000,0.000000000000000,0.958000000000000,0.042000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.075600000000000,0.050400000000000,0.117600000000000,0.000000000000000,0.000000000000000,0.756300000000000,0.000000000000000,0.000000000000000,0.974800000000000,0.025200000000000,0.000000000000000,0.000000000000000,0.966400000000000,0.016800000000000,0.016800000000000,0.983200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.016800000000000,0.000000000000000,6.792369275195012,18.326602923923836,73.709206900924869,26.290793099075096,0.000000000000000,0.000000000000000,46.191908936603625,29.879186236706872,23.928904826689482,0.000031736680244,0.032309882285635,0.117883362452482,0.000045378049870,100.000000000000000,17261.869999999998981,2000.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,1277.615786803002493,365.389491701098336,2430.944342087160749,0.974801259937003,0.385397196261682,0.844823527665766,0.999800039992001,1.000000000000000,334
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-5164614.754 -2677936.544, -5164656....",18639.788181369531230,18.639788181369532,0.949104660627787,318.675000000000011,3.196721311475410,20.899999999999999,24.000000000000000,103.000000000000000,96.480000000000004,30.260000000000002,14.100000000000000,0.000000000000000,55.640000000000001,0.000000000000000,0.000000000000000,0.619302742172345,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.008200000000000,0.000000000000000,0.991800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.565600000000000,0.278700000000000,0.155700000000000,0.844300000000000,0.155700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,34.194839273674610,53.892928377406491,11.912232348918900,0.000000000000000,54.780489043770409,13.266868126150957,31.952642830078627,0.000117513181764,0.031058578028131,0.117311225909030,0.000100366218354,100.000000000000000,3868.860000000000127,89.108910891089110,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1296.932330981916721,5287.866697468050006,0.704964751762412,0.532710280373832,0.804146435401226,0.999800039992001,2.000000000000000,390
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-3890716.958 -898474.936, -3890713.9...",7352.563602570774492,7.352563602570775,0.570651697479528,218.842999999999989,2.665343915343915,83.560000000000002,36.000000000000000,90.000000000000000,93.390000000000001,29.829999999999998,17.370000000000001,0.150000000000000,51.759999999999998,0.890000000000000,0.000000000000000,-0.196974020683646,99.879999999999995,0.120000000000000,0.928500000000000,0.014600000000000,0.054300000000000,0.001300000000000,0.000000000000000,0.001300000000000,0.429100000000000,0.161600000000000,0.166900000000000,0.121900000000000,0.038400000000000,0.079500000000000,0.002600000000000,0.000000000000000,0.998700000000000,0.001300000000000,0.000000000000000,0.000000000000000,0.973500000000000,0.023800000000000,0.002600000000000,0.887400000000000,0.080800000000000,0.030500000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.001300000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000029070225491,0.032954450738533,0.118833241983087,0.000048112787405,99.209999999999994,19323.349999999998545,961.538461538461547,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,486.490854788136858,811.613421159032669,0.930403479826009,0.704766355140187,0.848365107681029,0.997200559888022,1.000000000000000,2015
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-4157451.583 -573424.392, -4157474.5...",5185.085296568466219,5.185085296568467,0.822095149119573,2099.333999999999833,2.872340425531915,95.709999999999994,37.000000000000000,101.000000000000000,86.569999999999993,47.649999999999999,11.850000000000000,0.250000000000000,39.259999999999998,0.990000000000000,0.000000000000000,-0.035416414208469,100.000000000000000,0.000000000000000,0.992900000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.007100000000000,0.737600000000000,0.056700000000000,0.177300000000000,0.000000000000000,0.014200000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.957400000000000,0.028400000000000,0.014200000000000,0.971600000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.014200000000000,0.000000000000000,21.382140924663187,0.000000000000000,83.007552355743059,14.689138684519843,2.015395384172193,0.287913575564858,32.884011358103550,20.524083012020675,46.591905629875733,0.000025993265931,0.034204725825526,0.119566760337126,0.000043055032728,92.200000000000003,581.679999999999950,81.896551724137936,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,26050.510087316175486,738.810280349707796,2648.432513307378031,0.964501774911254,0.491285046728972,0.872328257207228,0.999800039992002,1.000000000000000,405

In [26]:
area_density = pd.read_excel('../../dataset/area_density.xlsx', skiprows=3, skipfooter=1)
area_density.columns = ['CD_FCU', 'name', 'area_km2', 'km', 'density_km2', 'dens_km']
area_density.drop(columns=['name', 'km', 'dens_km'], inplace=True)
area_density['CD_FCU'] = area_density['CD_FCU'].astype(int)
area_density

            CD_FCU           area_km2          density_km2
0      11000490002  0.037000000000000 1388.809999999999945
1      11000490006  0.145000000000000 3400.159999999999854
2      11001060003  0.269000000000000 2338.940000000000055
3      11001060004  0.294000000000000 1835.130000000000109
4      11001060005  0.605000000000000 1751.039999999999964
...            ...                ...                  ...
12343  53001080089 10.493000000000000 1123.279999999999973
12344  53001080090  0.216000000000000 1483.119999999999891
12345  53001080094  0.165000000000000 2242.559999999999945
12346  53001080095  0.593000000000000 1677.039999999999964
12347  53001080096  0.075000000000000 4710.899999999999636

[12348 rows x 3 columns]

In [27]:
final_version = join_data.merge(area_density, on='CD_FCU', how='left')
final_version

,CD_FCU,NM_FCU,CD_UF,NM_UF,SIGLA_UF,CD_MUN,NM_MUN,geometry,distance,dist_km,dist_norm,area,hh_density,age_idx,median_age,sex_ratio,literate,race_wht,race_blk,race_ylw,race_brn,race_ind,race_unk,depriv_idx,priv_hh,coll_hh,hh_type_1,hh_type_2,hh_type_3,hh_type_4,hh_type_5,hh_type_6,sanit_1,sanit_2,sanit_3,sanit_4,sanit_5,sanit_6,sanit_7,no_bath,excl_bath,shrd_bath,toilet,no_toilet,wtr_pipe,wtr_semi,no_wtr_pip,wtr_dist,wtr_deep,wtr_shal,wtr_spring,wtr_truck,wtr_rain,wtr_river,wtr_oth,wtr_area,veg_area,risk,slope_10,slope_20,slope_30,slope_30p,hand_6p,hand_3_6,hand_0_3,SO2,CO,O3,NO2,waste_coll,demo_dens,est_dens,est_edu,est_health,est_relig,est_agri,est_other,est_const,intra_veg,prim_hosp,inp_hosp,wtr_idx,sanit_idx,liv_a_idx,hh_idx,cluster,population,area_km2,density_km2
0,35503080069,Jardim Miliunas,35,São Paulo,SP,3550308,São Paulo,"POLYGON ((-5162009.388 -2692597.734, -5162042....",23646.846826038814470,23.646846826038814,0.533158552343469,1521.201999999999998,2.956632653061225,44.020000000000003,29.000000000000000,99.000000000000000,92.890000000000001,32.609999999999999,17.340000000000000,0.000000000000000,50.039999999999999,0.000000000000000,0.000000000000000,0.593881394151810,100.000000000000000,0.000000000000000,0.318900000000000,0.002600000000000,0.000000000000000,0.678600000000000,0.000000000000000,0.000000000000000,0.206600000000000,0.000000000000000,0.030600000000000,0.000000000000000,0.000000000000000,0.762800000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.994900000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005100000000000,0.000000000000000,0.000000000000000,0.000000000000000,50.965558831959356,49.034441168040658,0.000000000000000,0.000000000000000,35.578202056669660,26.962626321230797,37.459171622099561,0.000226338812134,0.032435898459901,0.117353676384719,0.000138925792410,98.719999999999999,45062.209999999999127,884.615384615384642,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,752.192509434099634,2071.724078601533165,0.997450127493625,0.451028037383178,0.681207545029720,0.321535692861428,1.000000000000000,1159,0.026000000000000,45062.209999999999127
1,42024040016,Rua Araranguá,42,Santa Catarina,SC,4202404,Blumenau,"POLYGON ((-5460228.537 -3115389.701, -5460231....",2544.012189292799121,2.544012189292799,0.080353569412576,518.619000000000028,2.809917355371901,60.270000000000003,34.000000000000000,102.000000000000000,96.629999999999995,79.709999999999994,4.120000000000000,0.000000000000000,16.180000000000000,0.000000000000000,0.000000000000000,-1.339049333599375,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.958700000000000,0.000000000000000,0.033100000000000,0.000000000000000,0.008300000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,3.783948041683024,100.000000000000000,0.120335888401926,9.787379757137918,12.635362314477181,77.456922039982985,88.808712208672446,6.551667421570913,4.639620369756640,0.000128408715662,0.030195952437025,0.119900281982149,0.000063380103705,100.000000000000000,2916.000000000000000,8.547008547008547,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,886.945621266084572,281.660799669791857,1167.193154171149445,1.000000000000000,0.978808411214953,0.872972435449063,0.999800039992001,0.000000000000000,340,0.117000000000000,2916.000000000000000
2,33045570554,Tiqui,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4840464.531 -2618564.009, -4840451....",28454.700967727036186,28.454700967727035,0.507650945554618,1200.328999999999951,2.834532374100720,87.500000000000000,34.000000000000000,90.000000000000000,96.579999999999998,29.440000000000001,23.100000000000001,0.000000000000000,47.460000000000001,0.000000000000000,0.000000000000000,-0.810630944817607,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.226089801895839,2.773910198104173,0.000000000000000,0.000000000000000,0.000000000000000,9.324049985563214,90.675950014436765,0.000190146016394,0.034092435378463,0.117907963273184,0.000099145903547,100.000000000000000,14189.510000000000218,821.428571428571445,100.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1003.263291531211848,1.000000000000000,1.000000000000000,0.853670564587899,0.999800039992001,0.000000000000000,394,0.028000000000000,14189.510000000000218
3,33045570104,Parque Nossa Senhora da Penha,33,Rio de Janeiro,RJ,3304557,Rio de Janeiro,"POLYGON ((-4810854.603 -2616904.986, -4810851....",1286.545036119262932,1.286545036119263,0.018809137112925,1200.328999999999951,2.836461126005362,98.980000000000004,35.000000000000000,84.000000000000000,91.760000000000005,37.430000000000000,14.080000000000000,0.090000000000000,47.539999999999999,0.850000000000000,0.000000000000000,-1.517390653235870,100.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.847200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.002700000000000,0.144800000000000,0.005400000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989300000000000,0.005400000000000,0.005400000000000,0.992000000000000,0.002700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.005400000000000,0.000000000000000,0.000000000000000,0.000000000000000,95.453633544999178,4.546366455000812,0.000000000000000,0.000000000000000,45.845887607786160,42.969202120337997,11.184910271875841,0.000173446921752,0.035576993041846,0.118095190761406,0.000125744957099,99.459999999999994,65726.529999999998836,2125.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,683.377208610892808,659.135305883393812,0.990750462476876,0.892920560747663,0.579645476589511,0.999999999999999,0.000000000000000,1058,0.016000000000000,65726.529999999998836
4,35095020135,Núcleo Residencial Jardim das Andorinhas II,35,São Paulo,SP,3509502,Campinas,"POLYGON ((-5233560.28 -2622317.23, -5233639.32...",5245.591377457038107,5.245591377457038,0.146824431092626,794.571000000000026,2.977375565610860,17.879999999999999,27.000000000000000,107.000000000000000,88.519999999999996,24.010000000000002,18.690000000000001,0.000000000000000,57.140000000000001,0.150000000000000,0.000000000000000,-0.248884424989380,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.570100000000000,0.000000000000000,0.009000000000000,0.000000000000000,0.031700000000000,0.389100000000000,0.000000000000000,0.000000000000000,0.995500000000000,0.004500000000000,0.000000000000000,0.000000000000000,0.991000000000000,0.000000000000000,0.009000000000000,0.991000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.009000000000000,0.000000000000000,1.118457571398694,77.471000482297413,2.910294857486170,43.722822077076380,53.366883065437442,0.000000000000000,94.236452727941781,5.763547272058226,0.000000000000000,0.000166720418881,0.032145364786926,0.117010048297412,0.000089746761517,100.000000000000000,17788.590000000000146,783.783783783783861,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,317.086033241421603,1383.163402628007816,1488.467146176819824,0.991000449977501,0.699696261682243,0.828075320854568,0.999800039992001,1.000000000000000,658,0.037000000000000,17788.590000000000146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12343,27043020123,Vila Santa Cruz,27,Alagoas,AL,2704302,Maceió,"POLYGON ((-3981406.076 -1070408.33, -3981639.1...",12464.347470914697624,12.464347470914698,0.490099152035993,509.319999999999993,3.095238095238095,16.460000000000001,27.000000000000000,104.000000000000000,88.359999999999999,25.640000000000001,8.890000000000001,0.340000000000000,64.620000000000005,0.510000000000000,0.000000000000000,4.283775096745155,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.026500000000000,0.000000000000000,0.015900000000000,0.957700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.989400000000000,0.000000000000000,0.010600000000000,0.719600000000000,0.269800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.010600000000000,0.000000000000000,0.000000000000000,0.000000000000000,97.081381283260754,2.918618716739250,0.000000000000000,0.000000000000000,9.076329708837251,43.275713431349082,47.647956859813675,0.000033033549837,0.032031551352307,0.118138291060697,0.000044508642802,6.350000000000000,19327.979999999999563,2700.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1523.970940459529402,2773.897971437058459,0.854507274636268,0.545140186915888,0.804361131811426,0.999800039992001,1.000000000000000,585,0.030000000000000,19327.979999999999563
12344,28003080047,Invasão da Jabotiana,28,Sergipe,SE,2800308,Aracaju,"POLYGON ((-4128645.906 -1225338.301, -4128644....",5943.694057307008734,5.943694057307009,0.187357972810060,182.163000000000011,2.806722689075630,36.619999999999997,30.000000000000000,104.000000000000000,85.170000000000002,25.149999999999999,16.170000000000002,0.000000000000000,58.680000000000000,0.000000000000000,0.000000000000000,-1.065465941070793,100.000000000000000,0.000000000000000,0.958000000000000,0.042000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.075600000000000,0.050400000000000,0.117600000000000,0.000000000000000,0.000000000000000,0.756300000000000,0.000000000000000,0.000000000000000,0.974800000000000,0.025200000000000,0.000000000000000,0.000000000000000,0.966400000000000,0.016800000000000,0.016800000000000,0.983200000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.016800000000000,0.000000000000000,6.792369275195012,18.326602923923836,73.709206900924869,26.290793099075096,0.000000000000000,0.000000000000000,46.191908936603625,29.879186236706872,23.928904826689482,0.000031736680244,0.032309882285635,0.117883362452482,0.000045378049870,100.000000000000000,17261.869999999998981,2000.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,1277.615786803002493,365.389491701098336,2430.944342087160749,0.974801259937003,0.385397196261682,0.844823527665766,0.999800039992001,1.000000000000000,334,0.019000000000000,17261.869999999998981
12345,35188000223,Residencial Bambi II,35,São Paulo,SP,3518800,Guarulhos,"POLYGON ((-5164614.754 -2677936.544, -5164656....",18639.788181369531230,18.639788181369532,0.949104660627787,318.675000000000011,3.196721311475410,20.899999999999999,24.000000000000000,103.000000000000000,96.480000000000004,30.260000000000002,14.100000000000000,0.000000000000000,55.640000000000001,0.000000000000000,0.000000000000000,0.619302742172345,100.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.008200000000000,0.000000000000000,0.991800000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.565600000000000,0.278700000000000,0.155700000000000,0.844300000000000,0.155700000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,34.194839273674610,53.892928377406491,11.912232348918900,0.000000000000000,54.780489043770409,13.266868126150957,31.952642830078627,0.000117513181764,0.031058578028131,0.117311225909030,0.000100366218354,100.000000000000000,3868.860000000000127,89.108910891089110,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,0.000000000000000,1296.932330981916721,5287.866697468050006,0.704964751762412,0.532710280373832,0.804146435401226,0.999800039992001,2.000000000000000,390,0.101000000000000,3868.860000000000127
12346,26116060881,Sítio Wanderley,26,Pernambuco,PE,2611606,Recife,"POLYGON ((-3890716.958 -898474.936, -3890713.9...",7352.563602570774492,7.352563602570775,0.570651697479528,218.842999999999989,2.665343915343915,83.560000000000002,36.000000000000000,90.000000000000000,93.390000000000001,29.829999999999998,17.370000000000001,0.150000000000000,51.759999999999998,0.890000000000000,0.000000000000000,-0.196974020683646,99.879999999999995,0.120000000000000,0.928500000000000,0.014600000000000,0.054300000000000,0.001300000000000,0.000000000000000,0.001300000000000,0.429100000000000,0.161600000000000,0.166900000000000,0.121900000000000,0.038400000000000,0.079500000000000,0.002600000000000,0.000000000000000,0.998700000000000,0.001300000000000,0.000000000000000,0.000000000000000,0.973500000000000,0.023800000000000,0.002600000000000,0.887400000000000,0.080800000000000,0.030500000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.001300000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000029070225491,0.032954450738533,0.118833241983087,0.000048112787405,99.209999999999994,19323.349999999998545,961.538461538461547,100.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,NaN,486.490854788136858,811.613421159032669,0.930403479826009,0.704766355140187,0.848365107681029,0.997200559888022,1.000000000000000,2015,0.104000000000000,19323.349999999998545
12347,24080030010,Resistência,24,Rio Grande do Norte,RN,2408003,Mossoró,"POLYGON ((-4157451.583 -573424.392, -4157474.5...",5185.085296568466219,5.185085296568467,0.822095149119573,2099.333999999999833,2.872340425531915,95.709999999999994,37.000000000000000,101.000000000000000,86.569999999999993,47.649999999999999,11.850000000000000,0.250000000000000,39.259999999999998,0.990000000000000,0.000000000000000,-0.035416414208469,100.000000000000000,0.000000000000000,0.992900000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.007100000000000,0.737600000000000,0.056700000000000,0.177300000000000,0.000000000000000,0.014200000000000,0.000000000000000,1.000000000000000,0.000000000000000,0.000000000000000,0.000000000000000,0.957400000000000,0.028400000000000,0.014200000000000,0.971600000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.007100000000000,0.000000000000000,0.000000000000000,0.014200000000000,0.000000000000000,21.382140924663187,0.000000000000000,83.007552355743059,14.689138684519843,2.015395384172193,0.287913575564858,32.884011358103550,20.524083012020675,46.591905629875733,0.000025993265931,0.034204725825526,0.119566760337126,0.000043055032728,92.200000000000003,581.679999999999950,81.896551724137936,0.000000000000000,0.000000000000000,100.000000000000000,0.000000000000000,100.000000000000000,100.000000000000000,26050.510087316175486,738.810280349707796,2648.432513307378031,0.964501774911254,0.491285046728972,0.872328257207228,0.999800039992002,1.000000000000000,405,0.696000000000000,581.679999999999950

In [28]:
# drop rows with missing cluster
final_version = final_version[final_version['cluster'].notna()]

# drop rows with missing wtr_area
final_version_no_missing_values = final_version[final_version['wtr_area'].notna()]

In [29]:
# save shp
final_version.to_file('../../dataset/shp/final_version.shp', driver='ESRI Shapefile')

final_version_no_missing_values.to_file('../../dataset/shp/final_version_no_missing_values.shp', driver='ESRI Shapefile')

/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_79767/149386657.py:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  final_version.to_file('../../dataset/shp/final_version.shp', driver='ESRI Shapefile')
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'density_km2' to 'density_km'
  ogr_write(
/var/folders/5l/x3ysgz0n0mvd7msxlmn75zhw0000gp/T/ipykernel_79767/149386657.py:4: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  final_version_no_missing_values.to_file('../../dataset/shp/final_version_no_missing_values.shp', driver='ESRI Shapefile')
/Users/joaosilva/workspace/phd/classify-slum/venv/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'density_km2' to 'density_km'
  ogr_write(

In [30]:
# to json
df = pd.DataFrame(final_version)
# drop geometry
df = df.drop(columns=['geometry'])
# save json
df.to_json('../../dataset/json/final_version.json', orient='records')